// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"io"
)


/**
 * DLG files contain the structure of conversations, in what is effectievly a state machine. Dialogs
 * contains string references into the TLK file that make up the actual words of the conversation.
 * Dialogs bear similarities to scripts; each state may have a series of trigger conditions, and
 * effect a series of actions. If the any of the triggers for a state evaluate to false, the state
 * is skipped and the triggers in the next state are evaluated - this occurs when entering into a
 * dialog state, and when presenting a list of responses.
 * 
 * ```
 * state 0:
 *     trigger: NumTimesTalkedTo(0)
 *     Text: "Hello, sailor!"
 * 
 * state 1:
 *     trigger: NumTimesTalkedToGT(5)
 *     Text: "Go away, already!"
 * 
 * state 2:
 *     Text: "Hail and well met, yada yada yada."
 * ```
 * Dialog always attempt to start at state 0. The first time this sample dialog is entered the
 * trigger in state 0 is true, hence the character responds "Hello, sailor!". Subsequent times the
 * dialog is entered the trigger in state 0 will be false, and state 1 is evaluated - this trigger
 * also fails and so state 2 is evaluated. This state evaluates true, and get the associated message
 * is displayed. If the dialog is initiaed five or more times, the trigger in state 1 will evaluate
 * to true and the message associated with that state will be displayed.
 * 
 * In addition to the triggers outlined above, states present a list of responses (aka transitions).
 * Each response may have a series of behaviours associated with it; the response text, a journal
 * entry or an action.
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/dlg_v1.htm
 * ">Source</a>
 */
type Dlg struct {
	Magic []byte
	Version []byte
	NumStates uint32
	OfsStates uint32
	NumTransitions uint32
	OfsTransitions uint32
	OfsStateTriggers uint32
	NumStateTriggers uint32
	OfsTransitionTriggers uint32
	NumTransitionTriggers uint32
	OfsActions uint32
	NumActions uint32
	ThreatFlags *Dlg_HeaderFlags
	_io *kaitai.Stream
	_root *Dlg
	_parent kaitai.Struct
	_raw_ThreatFlags []byte
	_f_actionTable bool
	actionTable *Dlg_ActionTable
	_f_stateTable bool
	stateTable *Dlg_StateTable
	_f_stateTriggerTable bool
	stateTriggerTable *Dlg_StateTriggerTable
	_f_transitionTable bool
	transitionTable *Dlg_TransitionTable
	_f_transitionTriggerTable bool
	transitionTriggerTable *Dlg_TransitionTriggerTable
}
func NewDlg() *Dlg {
	return &Dlg{
	}
}

func (this Dlg) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg) Read(io *kaitai.Stream, parent kaitai.Struct, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{68, 76, 71, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{68, 76, 71, 32}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = tmp2
	if !(bytes.Equal(this.Version, []uint8{86, 49, 46, 48})) {
		return kaitai.NewValidationNotEqualError([]uint8{86, 49, 46, 48}, this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumStates = uint32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsStates = uint32(tmp4)
	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumTransitions = uint32(tmp5)
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsTransitions = uint32(tmp6)
	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsStateTriggers = uint32(tmp7)
	tmp8, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumStateTriggers = uint32(tmp8)
	tmp9, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsTransitionTriggers = uint32(tmp9)
	tmp10, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumTransitionTriggers = uint32(tmp10)
	tmp11, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsActions = uint32(tmp11)
	tmp12, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumActions = uint32(tmp12)
	tmp13, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp13 = tmp13
	this._raw_ThreatFlags = tmp13
	_io__raw_ThreatFlags := kaitai.NewStream(bytes.NewReader(this._raw_ThreatFlags))
	tmp14 := NewDlg_HeaderFlags()
	err = tmp14.Read(_io__raw_ThreatFlags, this, this._root)
	if err != nil {
		return err
	}
	this.ThreatFlags = tmp14
	return err
}
func (this *Dlg) ActionTable() (v *Dlg_ActionTable, err error) {
	if (this._f_actionTable) {
		return this.actionTable, nil
	}
	this._f_actionTable = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsActions), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp15 := NewDlg_ActionTable()
	err = tmp15.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.actionTable = tmp15
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.actionTable, nil
}
func (this *Dlg) StateTable() (v *Dlg_StateTable, err error) {
	if (this._f_stateTable) {
		return this.stateTable, nil
	}
	this._f_stateTable = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsStates), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp16 := NewDlg_StateTable()
	err = tmp16.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.stateTable = tmp16
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.stateTable, nil
}
func (this *Dlg) StateTriggerTable() (v *Dlg_StateTriggerTable, err error) {
	if (this._f_stateTriggerTable) {
		return this.stateTriggerTable, nil
	}
	this._f_stateTriggerTable = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsStateTriggers), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp17 := NewDlg_StateTriggerTable()
	err = tmp17.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.stateTriggerTable = tmp17
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.stateTriggerTable, nil
}
func (this *Dlg) TransitionTable() (v *Dlg_TransitionTable, err error) {
	if (this._f_transitionTable) {
		return this.transitionTable, nil
	}
	this._f_transitionTable = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsTransitions), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp18 := NewDlg_TransitionTable()
	err = tmp18.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.transitionTable = tmp18
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.transitionTable, nil
}
func (this *Dlg) TransitionTriggerTable() (v *Dlg_TransitionTriggerTable, err error) {
	if (this._f_transitionTriggerTable) {
		return this.transitionTriggerTable, nil
	}
	this._f_transitionTriggerTable = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsTransitionTriggers), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp19 := NewDlg_TransitionTriggerTable()
	err = tmp19.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.transitionTriggerTable = tmp19
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.transitionTriggerTable, nil
}
type Dlg_ActionTable struct {
	Entries []*Dlg_TextEntry
	_io *kaitai.Stream
	_root *Dlg
	_parent *Dlg
}
func NewDlg_ActionTable() *Dlg_ActionTable {
	return &Dlg_ActionTable{
	}
}

func (this Dlg_ActionTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_ActionTable) Read(io *kaitai.Stream, parent *Dlg, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.NumActions); i++ {
		_ = i
		tmp20 := NewDlg_TextEntry()
		err = tmp20.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp20)
	}
	return err
}
type Dlg_HeaderFlags struct {
	TurnHostile bool
	EscapeArea bool
	DoNothing bool
	_io *kaitai.Stream
	_root *Dlg
	_parent *Dlg
}
func NewDlg_HeaderFlags() *Dlg_HeaderFlags {
	return &Dlg_HeaderFlags{
	}
}

func (this Dlg_HeaderFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_HeaderFlags) Read(io *kaitai.Stream, parent *Dlg, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp21, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TurnHostile = tmp21 != 0
	tmp22, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EscapeArea = tmp22 != 0
	tmp23, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DoNothing = tmp23 != 0
	return err
}
type Dlg_StateEntry struct {
	TextRef uint32
	FirstTransitionIndex uint32
	NumTransitions uint32
	StateTriggerIndex uint32
	_io *kaitai.Stream
	_root *Dlg
	_parent *Dlg_StateTable
	_f_transitions bool
	transitions []*Dlg_TransitionEntry
	_f_trigger bool
	trigger *Dlg_TextEntry
}
func NewDlg_StateEntry() *Dlg_StateEntry {
	return &Dlg_StateEntry{
	}
}

func (this Dlg_StateEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_StateEntry) Read(io *kaitai.Stream, parent *Dlg_StateTable, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp24, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TextRef = uint32(tmp24)
	tmp25, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FirstTransitionIndex = uint32(tmp25)
	tmp26, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumTransitions = uint32(tmp26)
	tmp27, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.StateTriggerIndex = uint32(tmp27)
	return err
}
func (this *Dlg_StateEntry) Transitions() (v []*Dlg_TransitionEntry, err error) {
	if (this._f_transitions) {
		return this.transitions, nil
	}
	this._f_transitions = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsTransitions + this.FirstTransitionIndex * 32), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumTransitions); i++ {
		_ = i
		tmp28 := NewDlg_TransitionEntry()
		err = tmp28.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.transitions = append(this.transitions, tmp28)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.transitions, nil
}
func (this *Dlg_StateEntry) Trigger() (v *Dlg_TextEntry, err error) {
	if (this._f_trigger) {
		return this.trigger, nil
	}
	this._f_trigger = true
	if (this.StateTriggerIndex != uint32(4294967295)) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this._root.OfsStateTriggers + this.StateTriggerIndex * 8), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp29 := NewDlg_TextEntry()
		err = tmp29.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.trigger = tmp29
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.trigger, nil
}
type Dlg_StateTable struct {
	Entries []*Dlg_StateEntry
	_io *kaitai.Stream
	_root *Dlg
	_parent *Dlg
}
func NewDlg_StateTable() *Dlg_StateTable {
	return &Dlg_StateTable{
	}
}

func (this Dlg_StateTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_StateTable) Read(io *kaitai.Stream, parent *Dlg, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.NumStates); i++ {
		_ = i
		tmp30 := NewDlg_StateEntry()
		err = tmp30.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp30)
	}
	return err
}
type Dlg_StateTriggerTable struct {
	Entries []*Dlg_TextEntry
	_io *kaitai.Stream
	_root *Dlg
	_parent *Dlg
}
func NewDlg_StateTriggerTable() *Dlg_StateTriggerTable {
	return &Dlg_StateTriggerTable{
	}
}

func (this Dlg_StateTriggerTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_StateTriggerTable) Read(io *kaitai.Stream, parent *Dlg, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.NumStateTriggers); i++ {
		_ = i
		tmp31 := NewDlg_TextEntry()
		err = tmp31.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp31)
	}
	return err
}
type Dlg_TextEntry struct {
	OfsText uint32
	LenText uint32
	_io *kaitai.Stream
	_root *Dlg
	_parent kaitai.Struct
	_f_text bool
	text string
}
func NewDlg_TextEntry() *Dlg_TextEntry {
	return &Dlg_TextEntry{
	}
}

func (this Dlg_TextEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_TextEntry) Read(io *kaitai.Stream, parent kaitai.Struct, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp32, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsText = uint32(tmp32)
	tmp33, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenText = uint32(tmp33)
	return err
}
func (this *Dlg_TextEntry) Text() (v string, err error) {
	if (this._f_text) {
		return this.text, nil
	}
	this._f_text = true
	thisIo := this._root._io
	_pos, err := thisIo.Pos()
	if err != nil {
		return "", err
	}
	_, err = thisIo.Seek(int64(this.OfsText), io.SeekStart)
	if err != nil {
		return "", err
	}
	tmp34, err := thisIo.ReadBytes(int(this.LenText))
	if err != nil {
		return "", err
	}
	tmp34 = tmp34
	this.text = string(tmp34)
	_, err = thisIo.Seek(_pos, io.SeekStart)
	if err != nil {
		return "", err
	}
	return this.text, nil
}
type Dlg_TransitionEntry struct {
	Flags *Dlg_TransitionEntry_Flags
	TextRef uint32
	JournalTextRef uint32
	TransitionTriggerIndex uint32
	TransitionActionIndex uint32
	NextStateResource string
	NextStateIndex uint32
	_io *kaitai.Stream
	_root *Dlg
	_parent kaitai.Struct
	_raw_Flags []byte
	_f_action bool
	action *Dlg_TextEntry
	_f_trigger bool
	trigger *Dlg_TextEntry
}
func NewDlg_TransitionEntry() *Dlg_TransitionEntry {
	return &Dlg_TransitionEntry{
	}
}

func (this Dlg_TransitionEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_TransitionEntry) Read(io *kaitai.Stream, parent kaitai.Struct, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp35, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp35 = tmp35
	this._raw_Flags = tmp35
	_io__raw_Flags := kaitai.NewStream(bytes.NewReader(this._raw_Flags))
	tmp36 := NewDlg_TransitionEntry_Flags()
	err = tmp36.Read(_io__raw_Flags, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp36
	tmp37, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TextRef = uint32(tmp37)
	tmp38, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.JournalTextRef = uint32(tmp38)
	tmp39, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TransitionTriggerIndex = uint32(tmp39)
	tmp40, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TransitionActionIndex = uint32(tmp40)
	tmp41, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp41 = tmp41
	this.NextStateResource = string(tmp41)
	tmp42, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NextStateIndex = uint32(tmp42)
	return err
}
func (this *Dlg_TransitionEntry) Action() (v *Dlg_TextEntry, err error) {
	if (this._f_action) {
		return this.action, nil
	}
	this._f_action = true
	if (this.Flags.WithAction) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this._root.OfsActions + this.TransitionActionIndex * 8), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp43 := NewDlg_TextEntry()
		err = tmp43.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.action = tmp43
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.action, nil
}
func (this *Dlg_TransitionEntry) Trigger() (v *Dlg_TextEntry, err error) {
	if (this._f_trigger) {
		return this.trigger, nil
	}
	this._f_trigger = true
	if (this.Flags.WithTrigger) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this._root.OfsTransitionTriggers + this.TransitionTriggerIndex * 8), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp44 := NewDlg_TextEntry()
		err = tmp44.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.trigger = tmp44
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.trigger, nil
}
type Dlg_TransitionEntry_Flags struct {
	WithText bool
	WithTrigger bool
	WithAction bool
	DialogEnd bool
	HasJournalEntry bool
	Interrupt bool
	AddUnsolvedQuest bool
	AddJournalNote bool
	AddSolvedQuest bool
	ImmediateAction bool
	ClearActions bool
	_io *kaitai.Stream
	_root *Dlg
	_parent *Dlg_TransitionEntry
}
func NewDlg_TransitionEntry_Flags() *Dlg_TransitionEntry_Flags {
	return &Dlg_TransitionEntry_Flags{
	}
}

func (this Dlg_TransitionEntry_Flags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_TransitionEntry_Flags) Read(io *kaitai.Stream, parent *Dlg_TransitionEntry, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp45, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.WithText = tmp45 != 0
	tmp46, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.WithTrigger = tmp46 != 0
	tmp47, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.WithAction = tmp47 != 0
	tmp48, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DialogEnd = tmp48 != 0
	tmp49, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HasJournalEntry = tmp49 != 0
	tmp50, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Interrupt = tmp50 != 0
	tmp51, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AddUnsolvedQuest = tmp51 != 0
	tmp52, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AddJournalNote = tmp52 != 0
	tmp53, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AddSolvedQuest = tmp53 != 0
	tmp54, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ImmediateAction = tmp54 != 0
	tmp55, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClearActions = tmp55 != 0
	return err
}
type Dlg_TransitionTable struct {
	Entries []*Dlg_TransitionEntry
	_io *kaitai.Stream
	_root *Dlg
	_parent *Dlg
}
func NewDlg_TransitionTable() *Dlg_TransitionTable {
	return &Dlg_TransitionTable{
	}
}

func (this Dlg_TransitionTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_TransitionTable) Read(io *kaitai.Stream, parent *Dlg, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.NumTransitions); i++ {
		_ = i
		tmp56 := NewDlg_TransitionEntry()
		err = tmp56.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp56)
	}
	return err
}
type Dlg_TransitionTriggerTable struct {
	Entries []*Dlg_TextEntry
	_io *kaitai.Stream
	_root *Dlg
	_parent *Dlg
}
func NewDlg_TransitionTriggerTable() *Dlg_TransitionTriggerTable {
	return &Dlg_TransitionTriggerTable{
	}
}

func (this Dlg_TransitionTriggerTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg_TransitionTriggerTable) Read(io *kaitai.Stream, parent *Dlg, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.NumTransitionTriggers); i++ {
		_ = i
		tmp57 := NewDlg_TextEntry()
		err = tmp57.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp57)
	}
	return err
}
