// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)


/**
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm
 * ">Source</a>
 */

type Eff_TargetType int
const (
	Eff_TargetType__None Eff_TargetType = 0
	Eff_TargetType__Self Eff_TargetType = 1
	Eff_TargetType__ProjectileTarget Eff_TargetType = 2
	Eff_TargetType__Party Eff_TargetType = 3
	Eff_TargetType__Everyone Eff_TargetType = 4
	Eff_TargetType__EveryoneButParty Eff_TargetType = 5
	Eff_TargetType__CasterGroup Eff_TargetType = 6
	Eff_TargetType__TargetGroup Eff_TargetType = 7
	Eff_TargetType__EveryoneButSelf Eff_TargetType = 8
	Eff_TargetType__OriginalCaster Eff_TargetType = 9
)
var values_Eff_TargetType = map[Eff_TargetType]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}}
func (v Eff_TargetType) isDefined() bool {
	_, ok := values_Eff_TargetType[v]
	return ok
}

type Eff_TimingMode int
const (
	Eff_TimingMode__InstantLimited Eff_TimingMode = 0
	Eff_TimingMode__InstantPermanentUntilDeath Eff_TimingMode = 1
	Eff_TimingMode__InstantWhileEquipped Eff_TimingMode = 2
	Eff_TimingMode__DelayLimited Eff_TimingMode = 3
	Eff_TimingMode__DelayPermanent Eff_TimingMode = 4
	Eff_TimingMode__DelayWhileEquipped Eff_TimingMode = 5
	Eff_TimingMode__LimitedAfterDuration Eff_TimingMode = 6
	Eff_TimingMode__PermanentAfterDuration Eff_TimingMode = 7
	Eff_TimingMode__EquippedAfterDuration Eff_TimingMode = 8
	Eff_TimingMode__InstantPermanent Eff_TimingMode = 9
	Eff_TimingMode__InstantLimitedTicks Eff_TimingMode = 10
	Eff_TimingMode__AbsoluteDuration Eff_TimingMode = 4096
)
var values_Eff_TimingMode = map[Eff_TimingMode]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 4096: {}}
func (v Eff_TimingMode) isDefined() bool {
	_, ok := values_Eff_TimingMode[v]
	return ok
}
type Eff struct {
	Magic []byte
	Version []byte
	Body *Eff_BodyV2
	_io *kaitai.Stream
	_root *Eff
	_parent kaitai.Struct
}
func NewEff() *Eff {
	return &Eff{
	}
}

func (this Eff) IO_() *kaitai.Stream {
	return this._io
}

func (this *Eff) Read(io *kaitai.Stream, parent kaitai.Struct, root *Eff) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{69, 70, 70, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{69, 70, 70, 32}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = tmp2
	if !(bytes.Equal(this.Version, []uint8{86, 50, 46, 48})) {
		return kaitai.NewValidationNotEqualError([]uint8{86, 50, 46, 48}, this.Version, this._io, "/seq/1")
	}
	tmp3 := NewEff_BodyV2(false)
	err = tmp3.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Body = tmp3
	return err
}

/**
 * This file format describes an effect (opcode) and its parameters.
 * The format is only ever found embedded in other files (e.g. ITM or SPL).
 * The engine appears to roll a probability for each valid target type, rather than one probability per attack.
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm
 * ">Source</a>
 */
type Eff_BodyV1 struct {
	Opcode uint16
	TargetType Eff_TargetType
	Power uint8
	Parameter1 uint32
	Parameter2 uint32
	TimingMode Eff_TimingMode
	DispelResistance *Eff_BodyV1_DispelResistance
	Duration uint32
	Probability1 uint8
	Probability2 uint8
	ResSpl string
	DiceThrown uint32
	DiceSides uint32
	SavingThrowType *Eff_SavingThrowType
	SavingThrowBonus uint32
	TobexStackingId uint32
	_io *kaitai.Stream
	_root *Eff
	_parent kaitai.Struct
	_raw_DispelResistance []byte
	_raw_SavingThrowType []byte
}
func NewEff_BodyV1() *Eff_BodyV1 {
	return &Eff_BodyV1{
	}
}

func (this Eff_BodyV1) IO_() *kaitai.Stream {
	return this._io
}

func (this *Eff_BodyV1) Read(io *kaitai.Stream, parent kaitai.Struct, root *Eff) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp4, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Opcode = uint16(tmp4)
	tmp5, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TargetType = Eff_TargetType(tmp5)
	tmp6, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Power = tmp6
	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter1 = uint32(tmp7)
	tmp8, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter2 = uint32(tmp8)
	tmp9, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TimingMode = Eff_TimingMode(tmp9)
	tmp10, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp10 = tmp10
	this._raw_DispelResistance = tmp10
	_io__raw_DispelResistance := kaitai.NewStream(bytes.NewReader(this._raw_DispelResistance))
	tmp11 := NewEff_BodyV1_DispelResistance()
	err = tmp11.Read(_io__raw_DispelResistance, this, this._root)
	if err != nil {
		return err
	}
	this.DispelResistance = tmp11
	tmp12, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Duration = uint32(tmp12)
	tmp13, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Probability1 = tmp13
	tmp14, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Probability2 = tmp14
	tmp15, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp15 = kaitai.BytesTerminate(tmp15, 0, false)
	this.ResSpl = string(tmp15)
	tmp16, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DiceThrown = uint32(tmp16)
	tmp17, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DiceSides = uint32(tmp17)
	tmp18, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp18 = tmp18
	this._raw_SavingThrowType = tmp18
	_io__raw_SavingThrowType := kaitai.NewStream(bytes.NewReader(this._raw_SavingThrowType))
	tmp19 := NewEff_SavingThrowType()
	err = tmp19.Read(_io__raw_SavingThrowType, this, this._root)
	if err != nil {
		return err
	}
	this.SavingThrowType = tmp19
	tmp20, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SavingThrowBonus = uint32(tmp20)
	tmp21, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TobexStackingId = uint32(tmp21)
	return err
}
type Eff_BodyV1_DispelResistance struct {
	Dispel bool
	BypassResistance bool
	_io *kaitai.Stream
	_root *Eff
	_parent *Eff_BodyV1
}
func NewEff_BodyV1_DispelResistance() *Eff_BodyV1_DispelResistance {
	return &Eff_BodyV1_DispelResistance{
	}
}

func (this Eff_BodyV1_DispelResistance) IO_() *kaitai.Stream {
	return this._io
}

func (this *Eff_BodyV1_DispelResistance) Read(io *kaitai.Stream, parent *Eff_BodyV1, root *Eff) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp22, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Dispel = tmp22 != 0
	tmp23, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BypassResistance = tmp23 != 0
	return err
}

type Eff_BodyV2_ParentResourceType int
const (
	Eff_BodyV2_ParentResourceType__None Eff_BodyV2_ParentResourceType = 0
	Eff_BodyV2_ParentResourceType__Spell Eff_BodyV2_ParentResourceType = 1
	Eff_BodyV2_ParentResourceType__Item Eff_BodyV2_ParentResourceType = 2
)
var values_Eff_BodyV2_ParentResourceType = map[Eff_BodyV2_ParentResourceType]struct{}{0: {}, 1: {}, 2: {}}
func (v Eff_BodyV2_ParentResourceType) isDefined() bool {
	_, ok := values_Eff_BodyV2_ParentResourceType[v]
	return ok
}
type Eff_BodyV2 struct {
	_unnamed0 []byte
	Opcode uint32
	TargetType Eff_TargetType
	Power uint32
	Parameter1 uint32
	Parameter2 uint32
	TimingMode Eff_TimingMode
	_unnamed7 uint16
	Duration uint32
	Probability1 uint16
	Probability2 uint16
	ResName string
	DiceThrown uint32
	DiceSides uint32
	SavingThrowType *Eff_SavingThrowType
	SaveBonus uint32
	Special uint32
	PrimaryType uint32
	Reserved uint32
	ParentResourceLowestAffectedLevel uint32
	ParentResourceHighestAffectedLevel uint32
	DispelResistance *Eff_BodyV2_DispelResistance
	Parameter3 uint32
	Parameter4 uint32
	Parameter5 uint32
	TimeApplied uint32
	ResName2 string
	ResName3 string
	CasterCoordinate *Eff_BodyV2_Coord
	TargetCoordinate *Eff_BodyV2_Coord
	ParentResourceType Eff_BodyV2_ParentResourceType
	ParentResource string
	ParentResourceFlags *Eff_BodyV2_ParentResourceFlags
	Projectile uint32
	ParentResourceSlot uint32
	VariableName string
	CasterLevel uint32
	FirstApply uint32
	SecondaryType uint32
	_unnamed39 []byte
	Embedded bool
	_io *kaitai.Stream
	_root *Eff
	_parent *Eff
	_raw_SavingThrowType []byte
	_raw_DispelResistance []byte
	_raw_ParentResourceFlags []byte
}
func NewEff_BodyV2(embedded bool) *Eff_BodyV2 {
	return &Eff_BodyV2{
		Embedded: embedded,
	}
}

func (this Eff_BodyV2) IO_() *kaitai.Stream {
	return this._io
}

func (this *Eff_BodyV2) Read(io *kaitai.Stream, parent *Eff, root *Eff) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp24, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp24 = tmp24
	this._unnamed0 = tmp24
	tmp25, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Opcode = uint32(tmp25)
	tmp26, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TargetType = Eff_TargetType(tmp26)
	tmp27, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Power = uint32(tmp27)
	tmp28, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter1 = uint32(tmp28)
	tmp29, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter2 = uint32(tmp29)
	tmp30, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.TimingMode = Eff_TimingMode(tmp30)
	tmp31, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this._unnamed7 = tmp31
	tmp32, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Duration = uint32(tmp32)
	tmp33, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Probability1 = uint16(tmp33)
	tmp34, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Probability2 = uint16(tmp34)
	tmp35, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp35 = kaitai.BytesTerminate(tmp35, 0, false)
	this.ResName = string(tmp35)
	tmp36, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DiceThrown = uint32(tmp36)
	tmp37, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DiceSides = uint32(tmp37)
	tmp38, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp38 = tmp38
	this._raw_SavingThrowType = tmp38
	_io__raw_SavingThrowType := kaitai.NewStream(bytes.NewReader(this._raw_SavingThrowType))
	tmp39 := NewEff_SavingThrowType()
	err = tmp39.Read(_io__raw_SavingThrowType, this, this._root)
	if err != nil {
		return err
	}
	this.SavingThrowType = tmp39
	tmp40, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SaveBonus = uint32(tmp40)
	tmp41, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Special = uint32(tmp41)
	tmp42, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PrimaryType = uint32(tmp42)
	tmp43, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Reserved = uint32(tmp43)
	tmp44, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ParentResourceLowestAffectedLevel = uint32(tmp44)
	tmp45, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ParentResourceHighestAffectedLevel = uint32(tmp45)
	tmp46, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp46 = tmp46
	this._raw_DispelResistance = tmp46
	_io__raw_DispelResistance := kaitai.NewStream(bytes.NewReader(this._raw_DispelResistance))
	tmp47 := NewEff_BodyV2_DispelResistance()
	err = tmp47.Read(_io__raw_DispelResistance, this, this._root)
	if err != nil {
		return err
	}
	this.DispelResistance = tmp47
	tmp48, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter3 = uint32(tmp48)
	tmp49, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter4 = uint32(tmp49)
	tmp50, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter5 = uint32(tmp50)
	tmp51, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TimeApplied = uint32(tmp51)
	tmp52, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp52 = kaitai.BytesTerminate(tmp52, 0, false)
	this.ResName2 = string(tmp52)
	tmp53, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp53 = kaitai.BytesTerminate(tmp53, 0, false)
	this.ResName3 = string(tmp53)
	tmp54 := NewEff_BodyV2_Coord()
	err = tmp54.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.CasterCoordinate = tmp54
	tmp55 := NewEff_BodyV2_Coord()
	err = tmp55.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TargetCoordinate = tmp55
	tmp56, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ParentResourceType = Eff_BodyV2_ParentResourceType(tmp56)
	tmp57, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp57 = kaitai.BytesTerminate(tmp57, 0, false)
	this.ParentResource = string(tmp57)
	tmp58, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp58 = tmp58
	this._raw_ParentResourceFlags = tmp58
	_io__raw_ParentResourceFlags := kaitai.NewStream(bytes.NewReader(this._raw_ParentResourceFlags))
	tmp59 := NewEff_BodyV2_ParentResourceFlags()
	err = tmp59.Read(_io__raw_ParentResourceFlags, this, this._root)
	if err != nil {
		return err
	}
	this.ParentResourceFlags = tmp59
	tmp60, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Projectile = uint32(tmp60)
	tmp61, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ParentResourceSlot = uint32(tmp61)
	tmp62, err := this._io.ReadBytes(int(32))
	if err != nil {
		return err
	}
	tmp62 = kaitai.BytesTerminate(tmp62, 0, false)
	this.VariableName = string(tmp62)
	tmp63, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CasterLevel = uint32(tmp63)
	tmp64, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FirstApply = uint32(tmp64)
	tmp65, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SecondaryType = uint32(tmp65)
	tmp66, err := this._io.ReadBytes(int(4 * 15))
	if err != nil {
		return err
	}
	tmp66 = tmp66
	this._unnamed39 = tmp66
	return err
}

/**
 * See `MSCHOOL.2DA`.
 */

/**
 * `VCC` in many effects.
 */

/**
 * See `MSECTYPE.2DA`.
 */
type Eff_BodyV2_Coord struct {
	X uint32
	Y uint32
	_io *kaitai.Stream
	_root *Eff
	_parent *Eff_BodyV2
}
func NewEff_BodyV2_Coord() *Eff_BodyV2_Coord {
	return &Eff_BodyV2_Coord{
	}
}

func (this Eff_BodyV2_Coord) IO_() *kaitai.Stream {
	return this._io
}

func (this *Eff_BodyV2_Coord) Read(io *kaitai.Stream, parent *Eff_BodyV2, root *Eff) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp67, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.X = uint32(tmp67)
	tmp68, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Y = uint32(tmp68)
	return err
}
type Eff_BodyV2_DispelResistance struct {
	Dispel bool
	BypassResistance bool
	BypassEe bool
	SelfTargeted bool
	_unnamed4 uint64
	EffectAppliedByIte bool
	_io *kaitai.Stream
	_root *Eff
	_parent *Eff_BodyV2
}
func NewEff_BodyV2_DispelResistance() *Eff_BodyV2_DispelResistance {
	return &Eff_BodyV2_DispelResistance{
	}
}

func (this Eff_BodyV2_DispelResistance) IO_() *kaitai.Stream {
	return this._io
}

func (this *Eff_BodyV2_DispelResistance) Read(io *kaitai.Stream, parent *Eff_BodyV2, root *Eff) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp69, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Dispel = tmp69 != 0
	tmp70, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BypassResistance = tmp70 != 0
	tmp71, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BypassEe = tmp71 != 0
	tmp72, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.SelfTargeted = tmp72 != 0
	tmp73, err := this._io.ReadBitsIntLe(27)
	if err != nil {
		return err
	}
	this._unnamed4 = tmp73
	tmp74, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EffectAppliedByIte = tmp74 != 0
	return err
}
type Eff_BodyV2_ParentResourceFlags struct {
	_unnamed0 uint64
	Hostile bool
	NoLosRequired bool
	AllowSpotting bool
	OutdoorsOnly bool
	NonMagicalAbility bool
	IgnoreWildSurge bool
	NonCombatAbility bool
	_io *kaitai.Stream
	_root *Eff
	_parent *Eff_BodyV2
}
func NewEff_BodyV2_ParentResourceFlags() *Eff_BodyV2_ParentResourceFlags {
	return &Eff_BodyV2_ParentResourceFlags{
	}
}

func (this Eff_BodyV2_ParentResourceFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Eff_BodyV2_ParentResourceFlags) Read(io *kaitai.Stream, parent *Eff_BodyV2, root *Eff) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp75, err := this._io.ReadBitsIntLe(10)
	if err != nil {
		return err
	}
	this._unnamed0 = tmp75
	tmp76, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Hostile = tmp76 != 0
	tmp77, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NoLosRequired = tmp77 != 0
	tmp78, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AllowSpotting = tmp78 != 0
	tmp79, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.OutdoorsOnly = tmp79 != 0
	tmp80, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NonMagicalAbility = tmp80 != 0
	tmp81, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgnoreWildSurge = tmp81 != 0
	tmp82, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NonCombatAbility = tmp82 != 0
	return err
}
type Eff_SavingThrowType struct {
	Spells bool
	Breath bool
	ParalyzePoisonDeath bool
	Wands bool
	PetrifyPolymorph bool
	EeSpells bool
	EeBreath bool
	EeParalyzePoisonDeath bool
	EeWands bool
	EePetrifyPolymorph bool
	IgnorePrimaryTarget bool
	IgnoreSecondaryTarget bool
	_unnamed12 uint64
	BypassMirrorImage bool
	IgnoreDifficulty bool
	Reserved bool
	_io *kaitai.Stream
	_root *Eff
	_parent kaitai.Struct
}
func NewEff_SavingThrowType() *Eff_SavingThrowType {
	return &Eff_SavingThrowType{
	}
}

func (this Eff_SavingThrowType) IO_() *kaitai.Stream {
	return this._io
}

func (this *Eff_SavingThrowType) Read(io *kaitai.Stream, parent kaitai.Struct, root *Eff) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp83, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Spells = tmp83 != 0
	tmp84, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Breath = tmp84 != 0
	tmp85, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ParalyzePoisonDeath = tmp85 != 0
	tmp86, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Wands = tmp86 != 0
	tmp87, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PetrifyPolymorph = tmp87 != 0
	tmp88, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EeSpells = tmp88 != 0
	tmp89, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EeBreath = tmp89 != 0
	tmp90, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EeParalyzePoisonDeath = tmp90 != 0
	tmp91, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EeWands = tmp91 != 0
	tmp92, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EePetrifyPolymorph = tmp92 != 0
	tmp93, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgnorePrimaryTarget = tmp93 != 0
	tmp94, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgnoreSecondaryTarget = tmp94 != 0
	tmp95, err := this._io.ReadBitsIntLe(13)
	if err != nil {
		return err
	}
	this._unnamed12 = tmp95
	tmp96, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BypassMirrorImage = tmp96 != 0
	tmp97, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgnoreDifficulty = tmp97 != 0
	tmp98, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Reserved = tmp98 != 0
	return err
}
