// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)


/**
 * This file format describes an effect (opcode) and its parameters.
 * The format is only ever found embedded in other files (e.g. ITM or SPL).
 * The engine appears to roll a probability for each valid target type, rather than one probability per attack.
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm
 * ">Source</a>
 */
type EffV1 struct {
	_io *kaitai.Stream
	_root *EffV1
	_parent kaitai.Struct
}
func NewEffV1() *EffV1 {
	return &EffV1{
	}
}

func (this EffV1) IO_() *kaitai.Stream {
	return this._io
}

func (this *EffV1) Read(io *kaitai.Stream, parent kaitai.Struct, root *EffV1) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type EffV1_DispelResistance struct {
	Dispel bool
	BypassResistance bool
	_io *kaitai.Stream
	_root *EffV1
	_parent *EffV1_Header
}
func NewEffV1_DispelResistance() *EffV1_DispelResistance {
	return &EffV1_DispelResistance{
	}
}

func (this EffV1_DispelResistance) IO_() *kaitai.Stream {
	return this._io
}

func (this *EffV1_DispelResistance) Read(io *kaitai.Stream, parent *EffV1_Header, root *EffV1) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Dispel = tmp1 != 0
	tmp2, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BypassResistance = tmp2 != 0
	return err
}
type EffV1_Header struct {
	OpcodeNumber uint16
	TargetType Eff_BodyV2_TargetType
	Power uint8
	Parameter1 uint32
	Parameter2 uint32
	TimingMode Eff_BodyV2_TimingMode
	DispelResistance *EffV1_DispelResistance
	Duration uint32
	Probability1 uint8
	Probability2 uint8
	ResName string
	DiceThrown uint32
	DiceSides uint32
	SavingThrowType *Eff_BodyV2_SavingThrowType
	SavingThrowBonus uint32
	TobexStackingId uint32
	_io *kaitai.Stream
	_root *EffV1
	_parent kaitai.Struct
	_raw_DispelResistance []byte
	_raw_SavingThrowType []byte
}
func NewEffV1_Header() *EffV1_Header {
	return &EffV1_Header{
	}
}

func (this EffV1_Header) IO_() *kaitai.Stream {
	return this._io
}

func (this *EffV1_Header) Read(io *kaitai.Stream, parent kaitai.Struct, root *EffV1) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp3, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.OpcodeNumber = uint16(tmp3)
	tmp4, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TargetType = Eff_BodyV2_TargetType(tmp4)
	tmp5, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Power = tmp5
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter1 = uint32(tmp6)
	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Parameter2 = uint32(tmp7)
	tmp8, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TimingMode = Eff_BodyV2_TimingMode(tmp8)
	tmp9, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this._raw_DispelResistance = tmp9
	_io__raw_DispelResistance := kaitai.NewStream(bytes.NewReader(this._raw_DispelResistance))
	tmp10 := NewEffV1_DispelResistance()
	err = tmp10.Read(_io__raw_DispelResistance, this, this._root)
	if err != nil {
		return err
	}
	this.DispelResistance = tmp10
	tmp11, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Duration = uint32(tmp11)
	tmp12, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Probability1 = tmp12
	tmp13, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Probability2 = tmp13
	tmp14, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp14 = kaitai.BytesTerminate(tmp14, 0, false)
	this.ResName = string(tmp14)
	tmp15, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DiceThrown = uint32(tmp15)
	tmp16, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DiceSides = uint32(tmp16)
	tmp17, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp17 = tmp17
	this._raw_SavingThrowType = tmp17
	_io__raw_SavingThrowType := kaitai.NewStream(bytes.NewReader(this._raw_SavingThrowType))
	tmp18 := NewEff_BodyV2_SavingThrowType()
	err = tmp18.Read(_io__raw_SavingThrowType, nil, nil)
	if err != nil {
		return err
	}
	this.SavingThrowType = tmp18
	tmp19, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SavingThrowBonus = uint32(tmp19)
	tmp20, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TobexStackingId = uint32(tmp20)
	return err
}
