// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"io"
)


/**
 * This file format is used to hold game information in save games.
 * The GAM file does not store area, creature or item information, instead, it stores information on the party members and the global variables which affect party members.
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm
 * ">Source</a>
 */

type Gam_CharacterSelection int
const (
	Gam_CharacterSelection__NotSelected Gam_CharacterSelection = 0
	Gam_CharacterSelection__Selected Gam_CharacterSelection = 1
	Gam_CharacterSelection__Dead Gam_CharacterSelection = 32768
)
var values_Gam_CharacterSelection = map[Gam_CharacterSelection]struct{}{0: {}, 1: {}, 32768: {}}
func (v Gam_CharacterSelection) isDefined() bool {
	_, ok := values_Gam_CharacterSelection[v]
	return ok
}

type Gam_LoadingProgress int
const (
	Gam_LoadingProgress__RestrictXpBg1 Gam_LoadingProgress = 0
	Gam_LoadingProgress__RestrictXpTotsc Gam_LoadingProgress = 1
	Gam_LoadingProgress__RestrictXpSoa Gam_LoadingProgress = 2
	Gam_LoadingProgress__ProcessingXnewarea2da Gam_LoadingProgress = 3
	Gam_LoadingProgress__CompleteXnewarea2da Gam_LoadingProgress = 4
	Gam_LoadingProgress__TobActive Gam_LoadingProgress = 5
)
var values_Gam_LoadingProgress = map[Gam_LoadingProgress]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}}
func (v Gam_LoadingProgress) isDefined() bool {
	_, ok := values_Gam_LoadingProgress[v]
	return ok
}

type Gam_Location int
const (
	Gam_Location__ExternalTotToh Gam_Location = 31
	Gam_Location__InternalTlk Gam_Location = 255
)
var values_Gam_Location = map[Gam_Location]struct{}{31: {}, 255: {}}
func (v Gam_Location) isDefined() bool {
	_, ok := values_Gam_Location[v]
	return ok
}

type Gam_PartyMember int
const (
	Gam_PartyMember__Player1 Gam_PartyMember = 0
	Gam_PartyMember__Player2 Gam_PartyMember = 1
	Gam_PartyMember__Player3 Gam_PartyMember = 2
	Gam_PartyMember__Player4 Gam_PartyMember = 3
	Gam_PartyMember__Player5 Gam_PartyMember = 4
	Gam_PartyMember__Player6 Gam_PartyMember = 5
	Gam_PartyMember__NotInParty Gam_PartyMember = 65535
)
var values_Gam_PartyMember = map[Gam_PartyMember]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 65535: {}}
func (v Gam_PartyMember) isDefined() bool {
	_, ok := values_Gam_PartyMember[v]
	return ok
}

type Gam_TextWindowSize int
const (
	Gam_TextWindowSize__Small Gam_TextWindowSize = 0
	Gam_TextWindowSize__Medium Gam_TextWindowSize = 1
	Gam_TextWindowSize__Unused Gam_TextWindowSize = 2
	Gam_TextWindowSize__Large Gam_TextWindowSize = 3
)
var values_Gam_TextWindowSize = map[Gam_TextWindowSize]struct{}{0: {}, 1: {}, 2: {}, 3: {}}
func (v Gam_TextWindowSize) isDefined() bool {
	_, ok := values_Gam_TextWindowSize[v]
	return ok
}
type Gam struct {
	Magic []byte
	Version []byte
	GameTime uint32
	SelectedFormation uint16
	FormationButton []uint16
	PartyGold uint32
	UseActiveArea Gam_PartyMember
	WeatherBitfield *Gam_WeatherFlags
	OfsPartyMembers uint32
	NumPartyMembers uint32
	OfsPartyInventory uint32
	NumPartyInventory uint32
	OfsNonPartyMembers uint32
	NumNonPartyMembers uint32
	OfsGlobalVariables uint32
	NumGlobalVariables uint32
	MainArea string
	OfsFamiliarExtra uint32
	NumJournalEntries uint32
	OfsJournalEntries uint32
	PartyReputation uint32
	CurrentArea string
	GuiFlags *Gam_GuiFlags
	LoadingProgress Gam_LoadingProgress
	OfsFamiliarInfo uint32
	OfsStoredLocations uint32
	NumStoredLocations uint32
	GameTimeSeconds uint32
	OfsPocketPlaneLocations uint32
	NumPocketPlaneLocations uint32
	ZoomLevel uint32
	RandomEncounterArea string
	CurrentWorldmap string
	CurrentCampagin string
	FamiliarOwner Gam_PartyMember
	RandomEncounterEntry string
	_io *kaitai.Stream
	_root *Gam
	_parent kaitai.Struct
	_raw_WeatherBitfield []byte
	_raw_GuiFlags []byte
	_f_familiarExtra bool
	familiarExtra string
	_f_familiarInfo bool
	familiarInfo *Gam_FamiliarInfo
	_f_globalVariables bool
	globalVariables []*Gam_GlobalVar
	_f_journalEntries bool
	journalEntries []*Gam_JournalEntry
	_f_nonPartyMembers bool
	nonPartyMembers []*Gam_Npcs
	_f_partyMembers bool
	partyMembers []*Gam_Npcs
	_f_pocketPlaneLocations bool
	pocketPlaneLocations []*Gam_PocketPlaneInfo
	_f_storedLocations bool
	storedLocations []*Gam_StoredLocationsInfo
}
func NewGam() *Gam {
	return &Gam{
	}
}

func (this Gam) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam) Read(io *kaitai.Stream, parent kaitai.Struct, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{71, 65, 77, 69})) {
		return kaitai.NewValidationNotEqualError([]uint8{71, 65, 77, 69}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = tmp2
	if !(bytes.Equal(this.Version, []uint8{86, 50, 46, 48})) {
		return kaitai.NewValidationNotEqualError([]uint8{86, 50, 46, 48}, this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GameTime = uint32(tmp3)
	tmp4, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.SelectedFormation = uint16(tmp4)
	for i := 0; i < int(5); i++ {
		_ = i
		tmp5, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.FormationButton = append(this.FormationButton, tmp5)
	}
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PartyGold = uint32(tmp6)
	tmp7, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.UseActiveArea = Gam_PartyMember(tmp7)
	tmp8, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp8 = tmp8
	this._raw_WeatherBitfield = tmp8
	_io__raw_WeatherBitfield := kaitai.NewStream(bytes.NewReader(this._raw_WeatherBitfield))
	tmp9 := NewGam_WeatherFlags()
	err = tmp9.Read(_io__raw_WeatherBitfield, this, this._root)
	if err != nil {
		return err
	}
	this.WeatherBitfield = tmp9
	tmp10, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsPartyMembers = uint32(tmp10)
	tmp11, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumPartyMembers = uint32(tmp11)
	tmp12, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsPartyInventory = uint32(tmp12)
	tmp13, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumPartyInventory = uint32(tmp13)
	tmp14, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsNonPartyMembers = uint32(tmp14)
	tmp15, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumNonPartyMembers = uint32(tmp15)
	tmp16, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsGlobalVariables = uint32(tmp16)
	tmp17, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumGlobalVariables = uint32(tmp17)
	tmp18, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp18 = kaitai.BytesTerminate(tmp18, 0, false)
	this.MainArea = string(tmp18)
	tmp19, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsFamiliarExtra = uint32(tmp19)
	tmp20, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumJournalEntries = uint32(tmp20)
	tmp21, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsJournalEntries = uint32(tmp21)
	tmp22, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PartyReputation = uint32(tmp22)
	tmp23, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp23 = kaitai.BytesTerminate(tmp23, 0, false)
	this.CurrentArea = string(tmp23)
	tmp24, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp24 = tmp24
	this._raw_GuiFlags = tmp24
	_io__raw_GuiFlags := kaitai.NewStream(bytes.NewReader(this._raw_GuiFlags))
	tmp25 := NewGam_GuiFlags()
	err = tmp25.Read(_io__raw_GuiFlags, this, this._root)
	if err != nil {
		return err
	}
	this.GuiFlags = tmp25
	tmp26, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LoadingProgress = Gam_LoadingProgress(tmp26)
	tmp27, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsFamiliarInfo = uint32(tmp27)
	tmp28, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsStoredLocations = uint32(tmp28)
	tmp29, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumStoredLocations = uint32(tmp29)
	tmp30, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GameTimeSeconds = uint32(tmp30)
	tmp31, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsPocketPlaneLocations = uint32(tmp31)
	tmp32, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumPocketPlaneLocations = uint32(tmp32)
	tmp33, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ZoomLevel = uint32(tmp33)
	tmp34, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp34 = kaitai.BytesTerminate(tmp34, 0, false)
	this.RandomEncounterArea = string(tmp34)
	tmp35, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp35 = kaitai.BytesTerminate(tmp35, 0, false)
	this.CurrentWorldmap = string(tmp35)
	tmp36, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp36 = kaitai.BytesTerminate(tmp36, 0, false)
	this.CurrentCampagin = string(tmp36)
	tmp37, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FamiliarOwner = Gam_PartyMember(tmp37)
	tmp38, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp38 = kaitai.BytesTerminate(tmp38, 0, false)
	this.RandomEncounterEntry = string(tmp38)
	return err
}
func (this *Gam) FamiliarExtra() (v string, err error) {
	if (this._f_familiarExtra) {
		return this.familiarExtra, nil
	}
	this._f_familiarExtra = true
	if (this.OfsFamiliarExtra != uint32(4294967295)) {
		_pos, err := this._io.Pos()
		if err != nil {
			return "", err
		}
		_, err = this._io.Seek(int64(this.OfsFamiliarExtra), io.SeekStart)
		if err != nil {
			return "", err
		}
		tmp39, err := this._io.ReadBytes(int(8))
		if err != nil {
			return "", err
		}
		tmp39 = kaitai.BytesTerminate(tmp39, 0, false)
		this.familiarExtra = string(tmp39)
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return "", err
		}
	}
	return this.familiarExtra, nil
}
func (this *Gam) FamiliarInfo() (v *Gam_FamiliarInfo, err error) {
	if (this._f_familiarInfo) {
		return this.familiarInfo, nil
	}
	this._f_familiarInfo = true
	if (this.OfsFamiliarInfo != uint32(4294967295)) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this.OfsFamiliarInfo), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp40 := NewGam_FamiliarInfo()
		err = tmp40.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.familiarInfo = tmp40
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.familiarInfo, nil
}
func (this *Gam) GlobalVariables() (v []*Gam_GlobalVar, err error) {
	if (this._f_globalVariables) {
		return this.globalVariables, nil
	}
	this._f_globalVariables = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsGlobalVariables), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumGlobalVariables); i++ {
		_ = i
		tmp41 := NewGam_GlobalVar()
		err = tmp41.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.globalVariables = append(this.globalVariables, tmp41)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.globalVariables, nil
}
func (this *Gam) JournalEntries() (v []*Gam_JournalEntry, err error) {
	if (this._f_journalEntries) {
		return this.journalEntries, nil
	}
	this._f_journalEntries = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsJournalEntries), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumJournalEntries); i++ {
		_ = i
		tmp42 := NewGam_JournalEntry()
		err = tmp42.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.journalEntries = append(this.journalEntries, tmp42)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.journalEntries, nil
}
func (this *Gam) NonPartyMembers() (v []*Gam_Npcs, err error) {
	if (this._f_nonPartyMembers) {
		return this.nonPartyMembers, nil
	}
	this._f_nonPartyMembers = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsNonPartyMembers), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumNonPartyMembers); i++ {
		_ = i
		tmp43 := NewGam_Npcs()
		err = tmp43.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.nonPartyMembers = append(this.nonPartyMembers, tmp43)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.nonPartyMembers, nil
}
func (this *Gam) PartyMembers() (v []*Gam_Npcs, err error) {
	if (this._f_partyMembers) {
		return this.partyMembers, nil
	}
	this._f_partyMembers = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsPartyMembers), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumPartyMembers); i++ {
		_ = i
		tmp44 := NewGam_Npcs()
		err = tmp44.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.partyMembers = append(this.partyMembers, tmp44)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.partyMembers, nil
}
func (this *Gam) PocketPlaneLocations() (v []*Gam_PocketPlaneInfo, err error) {
	if (this._f_pocketPlaneLocations) {
		return this.pocketPlaneLocations, nil
	}
	this._f_pocketPlaneLocations = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsPocketPlaneLocations), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumPocketPlaneLocations); i++ {
		_ = i
		tmp45 := NewGam_PocketPlaneInfo()
		err = tmp45.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.pocketPlaneLocations = append(this.pocketPlaneLocations, tmp45)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.pocketPlaneLocations, nil
}
func (this *Gam) StoredLocations() (v []*Gam_StoredLocationsInfo, err error) {
	if (this._f_storedLocations) {
		return this.storedLocations, nil
	}
	this._f_storedLocations = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsStoredLocations), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumStoredLocations); i++ {
		_ = i
		tmp46 := NewGam_StoredLocationsInfo()
		err = tmp46.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.storedLocations = append(this.storedLocations, tmp46)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.storedLocations, nil
}
type Gam_CharStats struct {
	MpvNameRef uint32
	MpvXpReward uint32
	TimeInParty uint32
	TimeJoined uint32
	IsPartyMember uint8
	_unnamed5 []byte
	FirstLetterCre uint8
	KillsXpChapter uint32
	KillsCountChapter uint32
	KillsXp uint32
	KillsCount uint32
	FavoriteSpellSpl []string
	FavoriteSpellCount []uint16
	FavoriteWeaponItm []string
	FavoriteWeaponTime []uint16
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam_Npcs
}
func NewGam_CharStats() *Gam_CharStats {
	return &Gam_CharStats{
	}
}

func (this Gam_CharStats) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_CharStats) Read(io *kaitai.Stream, parent *Gam_Npcs, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp47, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.MpvNameRef = uint32(tmp47)
	tmp48, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.MpvXpReward = uint32(tmp48)
	tmp49, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TimeInParty = uint32(tmp49)
	tmp50, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TimeJoined = uint32(tmp50)
	tmp51, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IsPartyMember = tmp51
	tmp52, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp52 = tmp52
	this._unnamed5 = tmp52
	tmp53, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.FirstLetterCre = tmp53
	tmp54, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.KillsXpChapter = uint32(tmp54)
	tmp55, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.KillsCountChapter = uint32(tmp55)
	tmp56, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.KillsXp = uint32(tmp56)
	tmp57, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.KillsCount = uint32(tmp57)
	for i := 0; i < int(4); i++ {
		_ = i
		tmp58, err := this._io.ReadBytes(int(8))
		if err != nil {
			return err
		}
		tmp58 = kaitai.BytesTerminate(tmp58, 0, false)
		this.FavoriteSpellSpl = append(this.FavoriteSpellSpl, string(tmp58))
	}
	for i := 0; i < int(4); i++ {
		_ = i
		tmp59, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.FavoriteSpellCount = append(this.FavoriteSpellCount, tmp59)
	}
	for i := 0; i < int(4); i++ {
		_ = i
		tmp60, err := this._io.ReadBytes(int(8))
		if err != nil {
			return err
		}
		tmp60 = kaitai.BytesTerminate(tmp60, 0, false)
		this.FavoriteWeaponItm = append(this.FavoriteWeaponItm, string(tmp60))
	}
	for i := 0; i < int(4); i++ {
		_ = i
		tmp61, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.FavoriteWeaponTime = append(this.FavoriteWeaponTime, tmp61)
	}
	return err
}
type Gam_FamiliarInfo struct {
	LawfulGoodFamiliarCre string
	LawfulNeutralFamiliarCre string
	LawfulEvilFamiliarCre string
	NeutralGoodFamiliarCre string
	NeutralFamiliarCre string
	NeutralEvilFamiliarCre string
	ChaoticGoodFamiliarCre string
	ChaoticNeutralFamiliarCre string
	ChaoticEvilFamiliarCre string
	OfsFamiliarRes uint32
	NumFamiliarLgLevel []uint32
	NumFamiliarLnLevel []uint32
	NumFamiliarCgLevel []uint32
	NumFamiliarNgLevel []uint32
	NumFamiliarTnLevel []uint32
	NumFamiliarNeLevel []uint32
	NumFamiliarLeLevel []uint32
	NumFamiliarCnLevel []uint32
	NumFamiliarCeLevel []uint32
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam
}
func NewGam_FamiliarInfo() *Gam_FamiliarInfo {
	return &Gam_FamiliarInfo{
	}
}

func (this Gam_FamiliarInfo) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_FamiliarInfo) Read(io *kaitai.Stream, parent *Gam, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp62, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp62 = kaitai.BytesTerminate(tmp62, 0, false)
	this.LawfulGoodFamiliarCre = string(tmp62)
	tmp63, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp63 = kaitai.BytesTerminate(tmp63, 0, false)
	this.LawfulNeutralFamiliarCre = string(tmp63)
	tmp64, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp64 = kaitai.BytesTerminate(tmp64, 0, false)
	this.LawfulEvilFamiliarCre = string(tmp64)
	tmp65, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp65 = kaitai.BytesTerminate(tmp65, 0, false)
	this.NeutralGoodFamiliarCre = string(tmp65)
	tmp66, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp66 = kaitai.BytesTerminate(tmp66, 0, false)
	this.NeutralFamiliarCre = string(tmp66)
	tmp67, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp67 = kaitai.BytesTerminate(tmp67, 0, false)
	this.NeutralEvilFamiliarCre = string(tmp67)
	tmp68, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp68 = kaitai.BytesTerminate(tmp68, 0, false)
	this.ChaoticGoodFamiliarCre = string(tmp68)
	tmp69, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp69 = kaitai.BytesTerminate(tmp69, 0, false)
	this.ChaoticNeutralFamiliarCre = string(tmp69)
	tmp70, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp70 = kaitai.BytesTerminate(tmp70, 0, false)
	this.ChaoticEvilFamiliarCre = string(tmp70)
	tmp71, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsFamiliarRes = uint32(tmp71)
	for i := 0; i < int(9); i++ {
		_ = i
		tmp72, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarLgLevel = append(this.NumFamiliarLgLevel, tmp72)
	}
	for i := 0; i < int(9); i++ {
		_ = i
		tmp73, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarLnLevel = append(this.NumFamiliarLnLevel, tmp73)
	}
	for i := 0; i < int(9); i++ {
		_ = i
		tmp74, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarCgLevel = append(this.NumFamiliarCgLevel, tmp74)
	}
	for i := 0; i < int(9); i++ {
		_ = i
		tmp75, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarNgLevel = append(this.NumFamiliarNgLevel, tmp75)
	}
	for i := 0; i < int(9); i++ {
		_ = i
		tmp76, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarTnLevel = append(this.NumFamiliarTnLevel, tmp76)
	}
	for i := 0; i < int(9); i++ {
		_ = i
		tmp77, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarNeLevel = append(this.NumFamiliarNeLevel, tmp77)
	}
	for i := 0; i < int(9); i++ {
		_ = i
		tmp78, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarLeLevel = append(this.NumFamiliarLeLevel, tmp78)
	}
	for i := 0; i < int(9); i++ {
		_ = i
		tmp79, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarCnLevel = append(this.NumFamiliarCnLevel, tmp79)
	}
	for i := 0; i < int(9); i++ {
		_ = i
		tmp80, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NumFamiliarCeLevel = append(this.NumFamiliarCeLevel, tmp80)
	}
	return err
}
type Gam_GlobalVar struct {
	VarName string
	VarType uint16
	RefVal uint16
	DwordVal uint32
	IntVal int32
	DoubleVal uint64
	ScriptName string
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam
}
func NewGam_GlobalVar() *Gam_GlobalVar {
	return &Gam_GlobalVar{
	}
}

func (this Gam_GlobalVar) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_GlobalVar) Read(io *kaitai.Stream, parent *Gam, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp81, err := this._io.ReadBytes(int(32))
	if err != nil {
		return err
	}
	tmp81 = kaitai.BytesTerminate(tmp81, 0, false)
	this.VarName = string(tmp81)
	tmp82, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.VarType = uint16(tmp82)
	tmp83, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.RefVal = uint16(tmp83)
	tmp84, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DwordVal = uint32(tmp84)
	tmp85, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.IntVal = int32(tmp85)
	tmp86, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.DoubleVal = uint64(tmp86)
	tmp87, err := this._io.ReadBytes(int(32))
	if err != nil {
		return err
	}
	tmp87 = kaitai.BytesTerminate(tmp87, 0, false)
	this.ScriptName = string(tmp87)
	return err
}
type Gam_GuiFlags struct {
	PartyAiEnabled bool
	TextWindowSize Gam_TextWindowSize
	_unnamed2 bool
	HideGui bool
	HideOptions bool
	HidePortraits bool
	ShowAutomapNotes bool
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam
}
func NewGam_GuiFlags() *Gam_GuiFlags {
	return &Gam_GuiFlags{
	}
}

func (this Gam_GuiFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_GuiFlags) Read(io *kaitai.Stream, parent *Gam, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp88, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PartyAiEnabled = tmp88 != 0
	tmp89, err := this._io.ReadBitsIntLe(2)
	if err != nil {
		return err
	}
	this.TextWindowSize = Gam_TextWindowSize(tmp89)
	tmp90, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this._unnamed2 = tmp90 != 0
	tmp91, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HideGui = tmp91 != 0
	tmp92, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HideOptions = tmp92 != 0
	tmp93, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HidePortraits = tmp93 != 0
	tmp94, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ShowAutomapNotes = tmp94 != 0
	return err
}
type Gam_JournalEntry struct {
	JournalTextRef uint32
	TimeSeconds uint32
	CurrentChapterNum uint8
	ReadByCharX uint8
	JournalSection *Gam_JournalSection
	Location Gam_Location
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam
	_raw_JournalSection []byte
}
func NewGam_JournalEntry() *Gam_JournalEntry {
	return &Gam_JournalEntry{
	}
}

func (this Gam_JournalEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_JournalEntry) Read(io *kaitai.Stream, parent *Gam, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp95, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.JournalTextRef = uint32(tmp95)
	tmp96, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TimeSeconds = uint32(tmp96)
	tmp97, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.CurrentChapterNum = tmp97
	tmp98, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ReadByCharX = tmp98
	tmp99, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp99 = tmp99
	this._raw_JournalSection = tmp99
	_io__raw_JournalSection := kaitai.NewStream(bytes.NewReader(this._raw_JournalSection))
	tmp100 := NewGam_JournalSection()
	err = tmp100.Read(_io__raw_JournalSection, this, this._root)
	if err != nil {
		return err
	}
	this.JournalSection = tmp100
	tmp101, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Location = Gam_Location(tmp101)
	return err
}
type Gam_JournalSection struct {
	Quests bool
	CompletedQuests bool
	JournalInfo bool
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam_JournalEntry
	_f_userNote bool
	userNote bool
}
func NewGam_JournalSection() *Gam_JournalSection {
	return &Gam_JournalSection{
	}
}

func (this Gam_JournalSection) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_JournalSection) Read(io *kaitai.Stream, parent *Gam_JournalEntry, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp102, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Quests = tmp102 != 0
	tmp103, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CompletedQuests = tmp103 != 0
	tmp104, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.JournalInfo = tmp104 != 0
	return err
}
func (this *Gam_JournalSection) UserNote() (v bool, err error) {
	if (this._f_userNote) {
		return this.userNote, nil
	}
	this._f_userNote = true
	this.userNote = bool(!( ((this.Quests) || (this.CompletedQuests) || (this.JournalInfo)) ))
	return this.userNote, nil
}
type Gam_Npcs struct {
	CharacterSelection Gam_CharacterSelection
	PartyOrder uint16
	OfsCreData uint32
	SizeCreData uint32
	CharacterName string
	CharacterOrientation uint32
	CharacterCurArea string
	CharacterX uint16
	CharacterY uint16
	ViewRectX uint16
	ViewRectY uint16
	ModalAction uint16
	Happiness uint16
	CountInteractedNpc []uint32
	QuickWeaponSlot []uint16
	QuickWeaponAbility []uint16
	QuickSpellSpl []string
	QuickItemSlot []uint16
	QuickItemAbility []uint16
	Name string
	Talkcount uint32
	CharacterStats *Gam_CharStats
	VoiceSet []byte
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam
}
func NewGam_Npcs() *Gam_Npcs {
	return &Gam_Npcs{
	}
}

func (this Gam_Npcs) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_Npcs) Read(io *kaitai.Stream, parent *Gam, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp105, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.CharacterSelection = Gam_CharacterSelection(tmp105)
	tmp106, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PartyOrder = uint16(tmp106)
	tmp107, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsCreData = uint32(tmp107)
	tmp108, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SizeCreData = uint32(tmp108)
	tmp109, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp109 = kaitai.BytesTerminate(tmp109, 0, false)
	this.CharacterName = string(tmp109)
	tmp110, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CharacterOrientation = uint32(tmp110)
	tmp111, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp111 = kaitai.BytesTerminate(tmp111, 0, false)
	this.CharacterCurArea = string(tmp111)
	tmp112, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.CharacterX = uint16(tmp112)
	tmp113, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.CharacterY = uint16(tmp113)
	tmp114, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ViewRectX = uint16(tmp114)
	tmp115, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ViewRectY = uint16(tmp115)
	tmp116, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ModalAction = uint16(tmp116)
	tmp117, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Happiness = uint16(tmp117)
	for i := 0; i < int(24); i++ {
		_ = i
		tmp118, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.CountInteractedNpc = append(this.CountInteractedNpc, tmp118)
	}
	for i := 0; i < int(4); i++ {
		_ = i
		tmp119, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.QuickWeaponSlot = append(this.QuickWeaponSlot, tmp119)
	}
	for i := 0; i < int(4); i++ {
		_ = i
		tmp120, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.QuickWeaponAbility = append(this.QuickWeaponAbility, tmp120)
	}
	for i := 0; i < int(3); i++ {
		_ = i
		tmp121, err := this._io.ReadBytes(int(8))
		if err != nil {
			return err
		}
		tmp121 = kaitai.BytesTerminate(tmp121, 0, false)
		this.QuickSpellSpl = append(this.QuickSpellSpl, string(tmp121))
	}
	for i := 0; i < int(3); i++ {
		_ = i
		tmp122, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.QuickItemSlot = append(this.QuickItemSlot, tmp122)
	}
	for i := 0; i < int(3); i++ {
		_ = i
		tmp123, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.QuickItemAbility = append(this.QuickItemAbility, tmp123)
	}
	tmp124, err := this._io.ReadBytes(int(32))
	if err != nil {
		return err
	}
	tmp124 = kaitai.BytesTerminate(tmp124, 0, false)
	this.Name = string(tmp124)
	tmp125, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Talkcount = uint32(tmp125)
	tmp126 := NewGam_CharStats()
	err = tmp126.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.CharacterStats = tmp126
	tmp127, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp127 = tmp127
	this.VoiceSet = tmp127
	return err
}

/**
 * See `slots.ids`
 */

/**
 * See `slots.ids`
 */
type Gam_PocketPlaneInfo struct {
	AreaAre string
	XCoord uint16
	YCoord uint16
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam
}
func NewGam_PocketPlaneInfo() *Gam_PocketPlaneInfo {
	return &Gam_PocketPlaneInfo{
	}
}

func (this Gam_PocketPlaneInfo) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_PocketPlaneInfo) Read(io *kaitai.Stream, parent *Gam, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp128, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp128 = kaitai.BytesTerminate(tmp128, 0, false)
	this.AreaAre = string(tmp128)
	tmp129, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.XCoord = uint16(tmp129)
	tmp130, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.YCoord = uint16(tmp130)
	return err
}
type Gam_StoredLocationsInfo struct {
	AreaAre string
	XCoord uint16
	YCoord uint16
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam
}
func NewGam_StoredLocationsInfo() *Gam_StoredLocationsInfo {
	return &Gam_StoredLocationsInfo{
	}
}

func (this Gam_StoredLocationsInfo) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_StoredLocationsInfo) Read(io *kaitai.Stream, parent *Gam, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp131, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp131 = kaitai.BytesTerminate(tmp131, 0, false)
	this.AreaAre = string(tmp131)
	tmp132, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.XCoord = uint16(tmp132)
	tmp133, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.YCoord = uint16(tmp133)
	return err
}
type Gam_WeatherFlags struct {
	Rain bool
	Snow bool
	LightRain bool
	MediumRain bool
	LightWind bool
	MediumWind bool
	RareLightning bool
	Lightning bool
	StormIncreasing bool
	_io *kaitai.Stream
	_root *Gam
	_parent *Gam
}
func NewGam_WeatherFlags() *Gam_WeatherFlags {
	return &Gam_WeatherFlags{
	}
}

func (this Gam_WeatherFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam_WeatherFlags) Read(io *kaitai.Stream, parent *Gam, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp134, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Rain = tmp134 != 0
	tmp135, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Snow = tmp135 != 0
	tmp136, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LightRain = tmp136 != 0
	tmp137, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.MediumRain = tmp137 != 0
	tmp138, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LightWind = tmp138 != 0
	tmp139, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.MediumWind = tmp139 != 0
	tmp140, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.RareLightning = tmp140 != 0
	tmp141, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Lightning = tmp141 != 0
	tmp142, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.StormIncreasing = tmp142 != 0
	return err
}
