// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"io"
)


/**
 * This file format describes an "item". Items include weapons, armor, books, scrolls, rings and more.
 * Items can have attached abilties, occuring either when a target creature it hit, or when the item is equipped.
 * ITM files have a similar structure to SPL files.
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm
 * ">Source</a>
 */

type Itm_AttackType int
const (
	Itm_AttackType__None Itm_AttackType = 0
	Itm_AttackType__Melee Itm_AttackType = 1
	Itm_AttackType__Ranged Itm_AttackType = 2
	Itm_AttackType__Magical Itm_AttackType = 3
	Itm_AttackType__Launcher Itm_AttackType = 4
)
var values_Itm_AttackType = map[Itm_AttackType]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}}
func (v Itm_AttackType) isDefined() bool {
	_, ok := values_Itm_AttackType[v]
	return ok
}

type Itm_ChargeDepletionBehavior int
const (
	Itm_ChargeDepletionBehavior__ItemRemains Itm_ChargeDepletionBehavior = 0
	Itm_ChargeDepletionBehavior__ItemVanishes Itm_ChargeDepletionBehavior = 1
	Itm_ChargeDepletionBehavior__ReplaceWithUsedUp Itm_ChargeDepletionBehavior = 2
	Itm_ChargeDepletionBehavior__ItemRecharges Itm_ChargeDepletionBehavior = 3
)
var values_Itm_ChargeDepletionBehavior = map[Itm_ChargeDepletionBehavior]struct{}{0: {}, 1: {}, 2: {}, 3: {}}
func (v Itm_ChargeDepletionBehavior) isDefined() bool {
	_, ok := values_Itm_ChargeDepletionBehavior[v]
	return ok
}

type Itm_DamageType int
const (
	Itm_DamageType__None Itm_DamageType = 0
	Itm_DamageType__Piercing Itm_DamageType = 1
	Itm_DamageType__Crushing Itm_DamageType = 2
	Itm_DamageType__Slashing Itm_DamageType = 3
	Itm_DamageType__Missile Itm_DamageType = 4
	Itm_DamageType__Fist Itm_DamageType = 5
	Itm_DamageType__PiercingCrushingBetter Itm_DamageType = 6
	Itm_DamageType__PiercingSlashingBetter Itm_DamageType = 7
	Itm_DamageType__CrushingSlashingWorse Itm_DamageType = 8
	Itm_DamageType__BluntMissile Itm_DamageType = 9
	Itm_DamageType__None2 Itm_DamageType = 10
	Itm_DamageType__None3 Itm_DamageType = 11
	Itm_DamageType__None4 Itm_DamageType = 12
	Itm_DamageType__None5 Itm_DamageType = 13
	Itm_DamageType__None6 Itm_DamageType = 14
	Itm_DamageType__None7 Itm_DamageType = 15
)
var values_Itm_DamageType = map[Itm_DamageType]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 11: {}, 12: {}, 13: {}, 14: {}, 15: {}}
func (v Itm_DamageType) isDefined() bool {
	_, ok := values_Itm_DamageType[v]
	return ok
}

type Itm_LauncherRequired int
const (
	Itm_LauncherRequired__None Itm_LauncherRequired = 0
	Itm_LauncherRequired__Bow Itm_LauncherRequired = 1
	Itm_LauncherRequired__Crossbow Itm_LauncherRequired = 2
	Itm_LauncherRequired__Sling Itm_LauncherRequired = 3
	Itm_LauncherRequired__Spear Itm_LauncherRequired = 40
	Itm_LauncherRequired__ThrowingAxe Itm_LauncherRequired = 100
)
var values_Itm_LauncherRequired = map[Itm_LauncherRequired]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 40: {}, 100: {}}
func (v Itm_LauncherRequired) isDefined() bool {
	_, ok := values_Itm_LauncherRequired[v]
	return ok
}

type Itm_Location int
const (
	Itm_Location__None Itm_Location = 0
	Itm_Location__Weapon Itm_Location = 1
	Itm_Location__Spell Itm_Location = 2
	Itm_Location__EquipmentItem Itm_Location = 3
	Itm_Location__Innate Itm_Location = 4
	Itm_Location__None2 Itm_Location = 5
	Itm_Location__None3 Itm_Location = 6
	Itm_Location__None4 Itm_Location = 7
)
var values_Itm_Location = map[Itm_Location]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}}
func (v Itm_Location) isDefined() bool {
	_, ok := values_Itm_Location[v]
	return ok
}

type Itm_TargetType int
const (
	Itm_TargetType__Invalid Itm_TargetType = 0
	Itm_TargetType__LivingActor Itm_TargetType = 1
	Itm_TargetType__Inventory Itm_TargetType = 2
	Itm_TargetType__DeadActor Itm_TargetType = 3
	Itm_TargetType__AnyPointWithinRange Itm_TargetType = 4
	Itm_TargetType__Caster Itm_TargetType = 5
	Itm_TargetType__Crash Itm_TargetType = 6
	Itm_TargetType__CasterEeOnly Itm_TargetType = 7
)
var values_Itm_TargetType = map[Itm_TargetType]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}}
func (v Itm_TargetType) isDefined() bool {
	_, ok := values_Itm_TargetType[v]
	return ok
}

type Itm_WeaponProficiency int
const (
	Itm_WeaponProficiency__None Itm_WeaponProficiency = 0
	Itm_WeaponProficiency__BastardSword Itm_WeaponProficiency = 89
	Itm_WeaponProficiency__LongSword Itm_WeaponProficiency = 90
	Itm_WeaponProficiency__ShortSword Itm_WeaponProficiency = 91
	Itm_WeaponProficiency__Axe Itm_WeaponProficiency = 92
	Itm_WeaponProficiency__TwoHandedSword Itm_WeaponProficiency = 93
	Itm_WeaponProficiency__Katana Itm_WeaponProficiency = 94
	Itm_WeaponProficiency__ScimitarWakizashiNinjaTo Itm_WeaponProficiency = 95
	Itm_WeaponProficiency__Dagger Itm_WeaponProficiency = 96
	Itm_WeaponProficiency__WarHammer Itm_WeaponProficiency = 97
	Itm_WeaponProficiency__Spear Itm_WeaponProficiency = 98
	Itm_WeaponProficiency__Halberd Itm_WeaponProficiency = 99
	Itm_WeaponProficiency__FlailMorningstar Itm_WeaponProficiency = 100
	Itm_WeaponProficiency__Mace Itm_WeaponProficiency = 101
	Itm_WeaponProficiency__Quarterstaff Itm_WeaponProficiency = 102
	Itm_WeaponProficiency__Crossbow Itm_WeaponProficiency = 103
	Itm_WeaponProficiency__LongBow Itm_WeaponProficiency = 104
	Itm_WeaponProficiency__ShortBow Itm_WeaponProficiency = 105
	Itm_WeaponProficiency__Darts Itm_WeaponProficiency = 106
	Itm_WeaponProficiency__Sling Itm_WeaponProficiency = 107
	Itm_WeaponProficiency__Blackjack Itm_WeaponProficiency = 108
	Itm_WeaponProficiency__Gun Itm_WeaponProficiency = 109
	Itm_WeaponProficiency__MartialArts Itm_WeaponProficiency = 110
	Itm_WeaponProficiency__TwoHandedWeaponSkill Itm_WeaponProficiency = 111
	Itm_WeaponProficiency__SwordAndShieldSkill Itm_WeaponProficiency = 112
	Itm_WeaponProficiency__SingleWeaponSkill Itm_WeaponProficiency = 113
	Itm_WeaponProficiency__TwoWeaponSkill Itm_WeaponProficiency = 114
	Itm_WeaponProficiency__Club Itm_WeaponProficiency = 115
	Itm_WeaponProficiency__ExtraProficiency2 Itm_WeaponProficiency = 116
	Itm_WeaponProficiency__ExtraProficiency3 Itm_WeaponProficiency = 117
	Itm_WeaponProficiency__ExtraProficiency4 Itm_WeaponProficiency = 118
	Itm_WeaponProficiency__ExtraProficiency5 Itm_WeaponProficiency = 119
	Itm_WeaponProficiency__ExtraProficiency6 Itm_WeaponProficiency = 120
	Itm_WeaponProficiency__ExtraProficiency7 Itm_WeaponProficiency = 121
	Itm_WeaponProficiency__ExtraProficiency8 Itm_WeaponProficiency = 122
	Itm_WeaponProficiency__ExtraProficiency9 Itm_WeaponProficiency = 123
	Itm_WeaponProficiency__ExtraProficiency10 Itm_WeaponProficiency = 124
	Itm_WeaponProficiency__ExtraProficiency11 Itm_WeaponProficiency = 125
	Itm_WeaponProficiency__ExtraProficiency12 Itm_WeaponProficiency = 126
	Itm_WeaponProficiency__ExtraProficiency13 Itm_WeaponProficiency = 127
	Itm_WeaponProficiency__ExtraProficiency14 Itm_WeaponProficiency = 128
	Itm_WeaponProficiency__ExtraProficiency15 Itm_WeaponProficiency = 129
	Itm_WeaponProficiency__ExtraProficiency16 Itm_WeaponProficiency = 130
	Itm_WeaponProficiency__ExtraProficiency17 Itm_WeaponProficiency = 131
	Itm_WeaponProficiency__ExtraProficiency18 Itm_WeaponProficiency = 132
	Itm_WeaponProficiency__ExtraProficiency19 Itm_WeaponProficiency = 133
	Itm_WeaponProficiency__ExtraProficiency20 Itm_WeaponProficiency = 134
)
var values_Itm_WeaponProficiency = map[Itm_WeaponProficiency]struct{}{0: {}, 89: {}, 90: {}, 91: {}, 92: {}, 93: {}, 94: {}, 95: {}, 96: {}, 97: {}, 98: {}, 99: {}, 100: {}, 101: {}, 102: {}, 103: {}, 104: {}, 105: {}, 106: {}, 107: {}, 108: {}, 109: {}, 110: {}, 111: {}, 112: {}, 113: {}, 114: {}, 115: {}, 116: {}, 117: {}, 118: {}, 119: {}, 120: {}, 121: {}, 122: {}, 123: {}, 124: {}, 125: {}, 126: {}, 127: {}, 128: {}, 129: {}, 130: {}, 131: {}, 132: {}, 133: {}, 134: {}}
func (v Itm_WeaponProficiency) isDefined() bool {
	_, ok := values_Itm_WeaponProficiency[v]
	return ok
}
type Itm struct {
	Magic []byte
	Version []byte
	UnidentifiedNameRef uint32
	IdentifiedNameRef uint32
	ItemOrSound *Itm_ItemOrSound
	Flags *Itm_HeaderFlags
	ItemType Sto_PurchasedItemType
	UsabilityBitmask *Itm_UsabilityFlags
	ItemAnimation string
	MinLevel uint16
	MinStrength uint16
	MinStrengthBonus uint8
	KitUsability1 *Itm_KitUsability1
	MinIntelligence uint8
	KitUsability2 *Itm_KitUsability2
	MinDexterity uint8
	KitUsability3 *Itm_KitUsability3
	MinWisdom uint8
	KitUsability4 *Itm_KitUsability4
	MinConstitution uint8
	WeaponProficiency Itm_WeaponProficiency
	MinCharisma uint16
	Price uint32
	StackAmount uint16
	InventoryIconBam string
	LoreToId uint16
	GroundIconBam string
	Weight uint32
	UnidentifiedDescriptionRef uint32
	IdentifiedDescriptionRef uint32
	DescriptionIconBam string
	Enchantment uint32
	OfsExtendedHeaders uint32
	NumExtendedHeaders uint16
	OfsFeatureBlocks uint32
	IdxEquippingFeatureBlocks uint16
	NumEquippingFeatureBlocks uint16
	_io *kaitai.Stream
	_root *Itm
	_parent kaitai.Struct
	_raw_Flags []byte
	_raw_UsabilityBitmask []byte
	_raw_KitUsability1 []byte
	_raw_KitUsability2 []byte
	_raw_KitUsability3 []byte
	_raw_KitUsability4 []byte
	_f_equippingFeatureBlocks bool
	equippingFeatureBlocks []*Eff_HeaderV1
	_f_extendedHeaders bool
	extendedHeaders []*Itm_ExtendedHeader
}
func NewItm() *Itm {
	return &Itm{
	}
}

func (this Itm) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm) Read(io *kaitai.Stream, parent kaitai.Struct, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{73, 84, 77, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{73, 84, 77, 32}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = tmp2
	if !(bytes.Equal(this.Version, []uint8{86, 49, 32, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{86, 49, 32, 32}, this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.UnidentifiedNameRef = uint32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IdentifiedNameRef = uint32(tmp4)
	tmp5 := NewItm_ItemOrSound()
	err = tmp5.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ItemOrSound = tmp5
	tmp6, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp6 = tmp6
	this._raw_Flags = tmp6
	_io__raw_Flags := kaitai.NewStream(bytes.NewReader(this._raw_Flags))
	tmp7 := NewItm_HeaderFlags()
	err = tmp7.Read(_io__raw_Flags, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp7
	tmp8, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ItemType = Sto_PurchasedItemType(tmp8)
	tmp9, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this._raw_UsabilityBitmask = tmp9
	_io__raw_UsabilityBitmask := kaitai.NewStream(bytes.NewReader(this._raw_UsabilityBitmask))
	tmp10 := NewItm_UsabilityFlags()
	err = tmp10.Read(_io__raw_UsabilityBitmask, this, this._root)
	if err != nil {
		return err
	}
	this.UsabilityBitmask = tmp10
	tmp11, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp11 = tmp11
	this.ItemAnimation = string(tmp11)
	tmp12, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.MinLevel = uint16(tmp12)
	tmp13, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.MinStrength = uint16(tmp13)
	tmp14, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MinStrengthBonus = tmp14
	tmp15, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp15 = tmp15
	this._raw_KitUsability1 = tmp15
	_io__raw_KitUsability1 := kaitai.NewStream(bytes.NewReader(this._raw_KitUsability1))
	tmp16 := NewItm_KitUsability1()
	err = tmp16.Read(_io__raw_KitUsability1, this, this._root)
	if err != nil {
		return err
	}
	this.KitUsability1 = tmp16
	tmp17, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MinIntelligence = tmp17
	tmp18, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp18 = tmp18
	this._raw_KitUsability2 = tmp18
	_io__raw_KitUsability2 := kaitai.NewStream(bytes.NewReader(this._raw_KitUsability2))
	tmp19 := NewItm_KitUsability2()
	err = tmp19.Read(_io__raw_KitUsability2, this, this._root)
	if err != nil {
		return err
	}
	this.KitUsability2 = tmp19
	tmp20, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MinDexterity = tmp20
	tmp21, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp21 = tmp21
	this._raw_KitUsability3 = tmp21
	_io__raw_KitUsability3 := kaitai.NewStream(bytes.NewReader(this._raw_KitUsability3))
	tmp22 := NewItm_KitUsability3()
	err = tmp22.Read(_io__raw_KitUsability3, this, this._root)
	if err != nil {
		return err
	}
	this.KitUsability3 = tmp22
	tmp23, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MinWisdom = tmp23
	tmp24, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp24 = tmp24
	this._raw_KitUsability4 = tmp24
	_io__raw_KitUsability4 := kaitai.NewStream(bytes.NewReader(this._raw_KitUsability4))
	tmp25 := NewItm_KitUsability4()
	err = tmp25.Read(_io__raw_KitUsability4, this, this._root)
	if err != nil {
		return err
	}
	this.KitUsability4 = tmp25
	tmp26, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MinConstitution = tmp26
	tmp27, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.WeaponProficiency = Itm_WeaponProficiency(tmp27)
	tmp28, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.MinCharisma = uint16(tmp28)
	tmp29, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Price = uint32(tmp29)
	tmp30, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.StackAmount = uint16(tmp30)
	tmp31, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp31 = kaitai.BytesTerminate(tmp31, 0, false)
	this.InventoryIconBam = string(tmp31)
	tmp32, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LoreToId = uint16(tmp32)
	tmp33, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp33 = kaitai.BytesTerminate(tmp33, 0, false)
	this.GroundIconBam = string(tmp33)
	tmp34, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Weight = uint32(tmp34)
	tmp35, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.UnidentifiedDescriptionRef = uint32(tmp35)
	tmp36, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IdentifiedDescriptionRef = uint32(tmp36)
	tmp37, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp37 = kaitai.BytesTerminate(tmp37, 0, false)
	this.DescriptionIconBam = string(tmp37)
	tmp38, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Enchantment = uint32(tmp38)
	tmp39, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsExtendedHeaders = uint32(tmp39)
	tmp40, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumExtendedHeaders = uint16(tmp40)
	tmp41, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsFeatureBlocks = uint32(tmp41)
	tmp42, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.IdxEquippingFeatureBlocks = uint16(tmp42)
	tmp43, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumEquippingFeatureBlocks = uint16(tmp43)
	return err
}
func (this *Itm) EquippingFeatureBlocks() (v []*Eff_HeaderV1, err error) {
	if (this._f_equippingFeatureBlocks) {
		return this.equippingFeatureBlocks, nil
	}
	this._f_equippingFeatureBlocks = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsFeatureBlocks + this.IdxEquippingFeatureBlocks * 48), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumEquippingFeatureBlocks); i++ {
		_ = i
		tmp44 := NewEff_HeaderV1()
		err = tmp44.Read(this._io, nil, nil)
		if err != nil {
			return nil, err
		}
		this.equippingFeatureBlocks = append(this.equippingFeatureBlocks, tmp44)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.equippingFeatureBlocks, nil
}
func (this *Itm) ExtendedHeaders() (v []*Itm_ExtendedHeader, err error) {
	if (this._f_extendedHeaders) {
		return this.extendedHeaders, nil
	}
	this._f_extendedHeaders = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsExtendedHeaders), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumExtendedHeaders); i++ {
		_ = i
		tmp45 := NewItm_ExtendedHeader()
		err = tmp45.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.extendedHeaders = append(this.extendedHeaders, tmp45)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.extendedHeaders, nil
}
type Itm_ExtendedHeader struct {
	AttackType Itm_AttackType
	IdRequirement *Itm_IdRequirement
	Location Itm_Location
	AlternativeDiceSides uint8
	UseIconBam string
	TargetType Itm_TargetType
	TargetCount uint8
	Range uint16
	LauncherRequired Itm_LauncherRequired
	AlternativeDiceThrown uint8
	SpeedFactor uint8
	AlternativeDamageBonus uint8
	Thac0Bonus uint16
	DiceSides uint8
	PrimaryType uint8
	DiceThrown uint8
	SecondaryType uint8
	DamageBonus uint16
	DamageType Itm_DamageType
	NumFeatureBlocks uint16
	IdxFeatureBlocks uint16
	MaxCharges uint16
	ChargeDepletionBehavior Itm_ChargeDepletionBehavior
	Flags *Itm_ExtensionHeaderFlags
	ProjectileAnimationPro uint16
	MeleeAnimation []byte
	IsArrow *Itm_ExtendedHeader_Bool
	IsBolt *Itm_ExtendedHeader_Bool
	IsBullet *Itm_ExtendedHeader_Bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm
	_raw_IdRequirement []byte
	_raw_Flags []byte
	_raw_IsArrow []byte
	_raw_IsBolt []byte
	_raw_IsBullet []byte
	_f_featureBlocks bool
	featureBlocks []*Eff_HeaderV1
}
func NewItm_ExtendedHeader() *Itm_ExtendedHeader {
	return &Itm_ExtendedHeader{
	}
}

func (this Itm_ExtendedHeader) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_ExtendedHeader) Read(io *kaitai.Stream, parent *Itm, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp46, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.AttackType = Itm_AttackType(tmp46)
	tmp47, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp47 = tmp47
	this._raw_IdRequirement = tmp47
	_io__raw_IdRequirement := kaitai.NewStream(bytes.NewReader(this._raw_IdRequirement))
	tmp48 := NewItm_IdRequirement()
	err = tmp48.Read(_io__raw_IdRequirement, this, this._root)
	if err != nil {
		return err
	}
	this.IdRequirement = tmp48
	tmp49, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Location = Itm_Location(tmp49)
	tmp50, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.AlternativeDiceSides = tmp50
	tmp51, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp51 = kaitai.BytesTerminate(tmp51, 0, false)
	this.UseIconBam = string(tmp51)
	tmp52, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TargetType = Itm_TargetType(tmp52)
	tmp53, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TargetCount = tmp53
	tmp54, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Range = uint16(tmp54)
	tmp55, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.LauncherRequired = Itm_LauncherRequired(tmp55)
	tmp56, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.AlternativeDiceThrown = tmp56
	tmp57, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SpeedFactor = tmp57
	tmp58, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.AlternativeDamageBonus = tmp58
	tmp59, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Thac0Bonus = uint16(tmp59)
	tmp60, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DiceSides = tmp60
	tmp61, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.PrimaryType = tmp61
	tmp62, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DiceThrown = tmp62
	tmp63, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SecondaryType = tmp63
	tmp64, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.DamageBonus = uint16(tmp64)
	tmp65, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.DamageType = Itm_DamageType(tmp65)
	tmp66, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumFeatureBlocks = uint16(tmp66)
	tmp67, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.IdxFeatureBlocks = uint16(tmp67)
	tmp68, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.MaxCharges = uint16(tmp68)
	tmp69, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ChargeDepletionBehavior = Itm_ChargeDepletionBehavior(tmp69)
	tmp70, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp70 = tmp70
	this._raw_Flags = tmp70
	_io__raw_Flags := kaitai.NewStream(bytes.NewReader(this._raw_Flags))
	tmp71 := NewItm_ExtensionHeaderFlags()
	err = tmp71.Read(_io__raw_Flags, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp71
	tmp72, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ProjectileAnimationPro = uint16(tmp72)
	tmp73, err := this._io.ReadBytes(int(6))
	if err != nil {
		return err
	}
	tmp73 = tmp73
	this.MeleeAnimation = tmp73
	tmp74, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp74 = tmp74
	this._raw_IsArrow = tmp74
	_io__raw_IsArrow := kaitai.NewStream(bytes.NewReader(this._raw_IsArrow))
	tmp75 := NewItm_ExtendedHeader_Bool()
	err = tmp75.Read(_io__raw_IsArrow, this, this._root)
	if err != nil {
		return err
	}
	this.IsArrow = tmp75
	tmp76, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp76 = tmp76
	this._raw_IsBolt = tmp76
	_io__raw_IsBolt := kaitai.NewStream(bytes.NewReader(this._raw_IsBolt))
	tmp77 := NewItm_ExtendedHeader_Bool()
	err = tmp77.Read(_io__raw_IsBolt, this, this._root)
	if err != nil {
		return err
	}
	this.IsBolt = tmp77
	tmp78, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp78 = tmp78
	this._raw_IsBullet = tmp78
	_io__raw_IsBullet := kaitai.NewStream(bytes.NewReader(this._raw_IsBullet))
	tmp79 := NewItm_ExtendedHeader_Bool()
	err = tmp79.Read(_io__raw_IsBullet, this, this._root)
	if err != nil {
		return err
	}
	this.IsBullet = tmp79
	return err
}
func (this *Itm_ExtendedHeader) FeatureBlocks() (v []*Eff_HeaderV1, err error) {
	if (this._f_featureBlocks) {
		return this.featureBlocks, nil
	}
	this._f_featureBlocks = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsFeatureBlocks + this.IdxFeatureBlocks * 48), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumFeatureBlocks); i++ {
		_ = i
		tmp80 := NewEff_HeaderV1()
		err = tmp80.Read(this._io, nil, nil)
		if err != nil {
			return nil, err
		}
		this.featureBlocks = append(this.featureBlocks, tmp80)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.featureBlocks, nil
}

/**
 * See `MSCHOOL.2DA`
 */

/**
 * See `MSECTYPE.2DA`
 */

/**
 * See `projectl.ids`/`missile.ids`
 */
type Itm_ExtendedHeader_Bool struct {
	Value bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm_ExtendedHeader
}
func NewItm_ExtendedHeader_Bool() *Itm_ExtendedHeader_Bool {
	return &Itm_ExtendedHeader_Bool{
	}
}

func (this Itm_ExtendedHeader_Bool) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_ExtendedHeader_Bool) Read(io *kaitai.Stream, parent *Itm_ExtendedHeader, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp81, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Value = tmp81 != 0
	return err
}
type Itm_ExtensionHeaderFlags struct {
	AddStrengthBonus bool
	Breakable bool
	DamageStrengthBonus bool
	Thac0StrengthBonus bool
	_unnamed4 []bool
	BreaksSanctuaryInvisibility bool
	Hostile bool
	RechargeAfterResting bool
	_unnamed8 []bool
	ToggleBackstab bool
	CannotTargetInvisible bool
	_unnamed11 []bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm_ExtendedHeader
}
func NewItm_ExtensionHeaderFlags() *Itm_ExtensionHeaderFlags {
	return &Itm_ExtensionHeaderFlags{
	}
}

func (this Itm_ExtensionHeaderFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_ExtensionHeaderFlags) Read(io *kaitai.Stream, parent *Itm_ExtendedHeader, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp82, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AddStrengthBonus = tmp82 != 0
	tmp83, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Breakable = tmp83 != 0
	tmp84, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DamageStrengthBonus = tmp84 != 0
	tmp85, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Thac0StrengthBonus = tmp85 != 0
	for i := 0; i < int(5); i++ {
		_ = i
		tmp86, err := this._io.ReadBitsIntLe(1)
		if err != nil {
			return err
		}
		this._unnamed4 = append(this._unnamed4, tmp86 != 0)
	}
	tmp87, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BreaksSanctuaryInvisibility = tmp87 != 0
	tmp88, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Hostile = tmp88 != 0
	tmp89, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.RechargeAfterResting = tmp89 != 0
	for i := 0; i < int(13); i++ {
		_ = i
		tmp90, err := this._io.ReadBitsIntLe(1)
		if err != nil {
			return err
		}
		this._unnamed8 = append(this._unnamed8, tmp90 != 0)
	}
	tmp91, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ToggleBackstab = tmp91 != 0
	tmp92, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CannotTargetInvisible = tmp92 != 0
	for i := 0; i < int(5); i++ {
		_ = i
		tmp93, err := this._io.ReadBitsIntLe(1)
		if err != nil {
			return err
		}
		this._unnamed11 = append(this._unnamed11, tmp93 != 0)
	}
	return err
}
type Itm_HeaderFlags struct {
	Unsellable bool
	TwoHanded bool
	MovableDroppable bool
	Displayable bool
	Cursed bool
	CannotScribeToSpellbook bool
	Magical bool
	LeftHanded bool
	Silver bool
	ColdIron bool
	StolenOffHanded bool
	ConversableUnsellable bool
	FakeTwoHandded bool
	ForbidOffHandWeapon bool
	UsableInInventory bool
	Adamantine bool
	_unnamed16 []bool
	Undispellable bool
	ToggleCriticalHitAversion bool
	_unnamed19 []bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm
}
func NewItm_HeaderFlags() *Itm_HeaderFlags {
	return &Itm_HeaderFlags{
	}
}

func (this Itm_HeaderFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_HeaderFlags) Read(io *kaitai.Stream, parent *Itm, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp94, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Unsellable = tmp94 != 0
	tmp95, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TwoHanded = tmp95 != 0
	tmp96, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.MovableDroppable = tmp96 != 0
	tmp97, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Displayable = tmp97 != 0
	tmp98, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Cursed = tmp98 != 0
	tmp99, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CannotScribeToSpellbook = tmp99 != 0
	tmp100, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Magical = tmp100 != 0
	tmp101, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LeftHanded = tmp101 != 0
	tmp102, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Silver = tmp102 != 0
	tmp103, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ColdIron = tmp103 != 0
	tmp104, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.StolenOffHanded = tmp104 != 0
	tmp105, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ConversableUnsellable = tmp105 != 0
	tmp106, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FakeTwoHandded = tmp106 != 0
	tmp107, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ForbidOffHandWeapon = tmp107 != 0
	tmp108, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UsableInInventory = tmp108 != 0
	tmp109, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Adamantine = tmp109 != 0
	for i := 0; i < int(8); i++ {
		_ = i
		tmp110, err := this._io.ReadBitsIntLe(1)
		if err != nil {
			return err
		}
		this._unnamed16 = append(this._unnamed16, tmp110 != 0)
	}
	tmp111, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Undispellable = tmp111 != 0
	tmp112, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ToggleCriticalHitAversion = tmp112 != 0
	for i := 0; i < int(6); i++ {
		_ = i
		tmp113, err := this._io.ReadBitsIntLe(1)
		if err != nil {
			return err
		}
		this._unnamed19 = append(this._unnamed19, tmp113 != 0)
	}
	return err
}
type Itm_IdRequirement struct {
	IdRequired bool
	NonIdRequired bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm_ExtendedHeader
}
func NewItm_IdRequirement() *Itm_IdRequirement {
	return &Itm_IdRequirement{
	}
}

func (this Itm_IdRequirement) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_IdRequirement) Read(io *kaitai.Stream, parent *Itm_ExtendedHeader, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp114, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IdRequired = tmp114 != 0
	tmp115, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NonIdRequired = tmp115 != 0
	return err
}
type Itm_ItemOrSound struct {
	BgReplacementItemItm string
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm
	_f_pstDropSoundWav bool
	pstDropSoundWav string
}
func NewItm_ItemOrSound() *Itm_ItemOrSound {
	return &Itm_ItemOrSound{
	}
}

func (this Itm_ItemOrSound) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_ItemOrSound) Read(io *kaitai.Stream, parent *Itm, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp116, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp116 = kaitai.BytesTerminate(tmp116, 0, false)
	this.BgReplacementItemItm = string(tmp116)
	return err
}
func (this *Itm_ItemOrSound) PstDropSoundWav() (v string, err error) {
	if (this._f_pstDropSoundWav) {
		return this.pstDropSoundWav, nil
	}
	this._f_pstDropSoundWav = true
	this.pstDropSoundWav = string(this.BgReplacementItemItm)
	return this.pstDropSoundWav, nil
}
type Itm_KitUsability1 struct {
	ClericOfTalos bool
	ClericOfHelm bool
	ClericOfLathlander bool
	TotemicDruid bool
	ShapeshifterDruid bool
	AvengerDruid bool
	Barbarian bool
	Wildmage bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm
}
func NewItm_KitUsability1() *Itm_KitUsability1 {
	return &Itm_KitUsability1{
	}
}

func (this Itm_KitUsability1) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_KitUsability1) Read(io *kaitai.Stream, parent *Itm, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp117, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericOfTalos = tmp117 != 0
	tmp118, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericOfHelm = tmp118 != 0
	tmp119, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericOfLathlander = tmp119 != 0
	tmp120, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TotemicDruid = tmp120 != 0
	tmp121, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ShapeshifterDruid = tmp121 != 0
	tmp122, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AvengerDruid = tmp122 != 0
	tmp123, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Barbarian = tmp123 != 0
	tmp124, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Wildmage = tmp124 != 0
	return err
}
type Itm_KitUsability2 struct {
	StalkerRanger bool
	BeastmasterRanger bool
	AssassinThief bool
	BountyHunterThief bool
	SwashbucklerThief bool
	BladeBard bool
	JesterBard bool
	SkaldBard bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm
}
func NewItm_KitUsability2() *Itm_KitUsability2 {
	return &Itm_KitUsability2{
	}
}

func (this Itm_KitUsability2) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_KitUsability2) Read(io *kaitai.Stream, parent *Itm, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp125, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.StalkerRanger = tmp125 != 0
	tmp126, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BeastmasterRanger = tmp126 != 0
	tmp127, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AssassinThief = tmp127 != 0
	tmp128, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BountyHunterThief = tmp128 != 0
	tmp129, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.SwashbucklerThief = tmp129 != 0
	tmp130, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BladeBard = tmp130 != 0
	tmp131, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.JesterBard = tmp131 != 0
	tmp132, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.SkaldBard = tmp132 != 0
	return err
}
type Itm_KitUsability3 struct {
	Diviner bool
	Enchanter bool
	Illusionist bool
	Invoker bool
	Necromancer bool
	Transmuter bool
	All bool
	Ferlain bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm
}
func NewItm_KitUsability3() *Itm_KitUsability3 {
	return &Itm_KitUsability3{
	}
}

func (this Itm_KitUsability3) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_KitUsability3) Read(io *kaitai.Stream, parent *Itm, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp133, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Diviner = tmp133 != 0
	tmp134, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Enchanter = tmp134 != 0
	tmp135, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Illusionist = tmp135 != 0
	tmp136, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Invoker = tmp136 != 0
	tmp137, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Necromancer = tmp137 != 0
	tmp138, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Transmuter = tmp138 != 0
	tmp139, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.All = tmp139 != 0
	tmp140, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Ferlain = tmp140 != 0
	return err
}
type Itm_KitUsability4 struct {
	BerserkerFighter bool
	WizardslayerFighter bool
	KensaiFighter bool
	CavalierPaladin bool
	InquisiterPaladin bool
	UndeadHunterPaladin bool
	Abjurer bool
	Conjurer bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm
}
func NewItm_KitUsability4() *Itm_KitUsability4 {
	return &Itm_KitUsability4{
	}
}

func (this Itm_KitUsability4) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_KitUsability4) Read(io *kaitai.Stream, parent *Itm, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp141, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BerserkerFighter = tmp141 != 0
	tmp142, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.WizardslayerFighter = tmp142 != 0
	tmp143, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.KensaiFighter = tmp143 != 0
	tmp144, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CavalierPaladin = tmp144 != 0
	tmp145, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.InquisiterPaladin = tmp145 != 0
	tmp146, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UndeadHunterPaladin = tmp146 != 0
	tmp147, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Abjurer = tmp147 != 0
	tmp148, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Conjurer = tmp148 != 0
	return err
}
type Itm_UsabilityFlags struct {
	ChaoticPrefix bool
	Evil bool
	Good bool
	Neutral bool
	LawfulPrefix bool
	NeutralPrefix bool
	Bard bool
	Cleric bool
	ClericMage bool
	ClericThief bool
	ClericRanger bool
	Fighter bool
	FighterDruid bool
	FighterMage bool
	FighterCleric bool
	FighterMageCleric bool
	FighterMageThief bool
	FighterThief bool
	Mage bool
	MageThief bool
	Paladin bool
	Ranger bool
	Thief bool
	Elf bool
	Dwarf bool
	HalfElf bool
	Halfling bool
	Human bool
	Gnome bool
	Monk bool
	Druid bool
	HalfOrc bool
	_io *kaitai.Stream
	_root *Itm
	_parent *Itm
}
func NewItm_UsabilityFlags() *Itm_UsabilityFlags {
	return &Itm_UsabilityFlags{
	}
}

func (this Itm_UsabilityFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Itm_UsabilityFlags) Read(io *kaitai.Stream, parent *Itm, root *Itm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp149, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ChaoticPrefix = tmp149 != 0
	tmp150, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Evil = tmp150 != 0
	tmp151, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Good = tmp151 != 0
	tmp152, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Neutral = tmp152 != 0
	tmp153, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LawfulPrefix = tmp153 != 0
	tmp154, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NeutralPrefix = tmp154 != 0
	tmp155, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Bard = tmp155 != 0
	tmp156, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Cleric = tmp156 != 0
	tmp157, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericMage = tmp157 != 0
	tmp158, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericThief = tmp158 != 0
	tmp159, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericRanger = tmp159 != 0
	tmp160, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Fighter = tmp160 != 0
	tmp161, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FighterDruid = tmp161 != 0
	tmp162, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FighterMage = tmp162 != 0
	tmp163, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FighterCleric = tmp163 != 0
	tmp164, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FighterMageCleric = tmp164 != 0
	tmp165, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FighterMageThief = tmp165 != 0
	tmp166, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FighterThief = tmp166 != 0
	tmp167, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Mage = tmp167 != 0
	tmp168, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.MageThief = tmp168 != 0
	tmp169, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Paladin = tmp169 != 0
	tmp170, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Ranger = tmp170 != 0
	tmp171, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Thief = tmp171 != 0
	tmp172, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Elf = tmp172 != 0
	tmp173, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Dwarf = tmp173 != 0
	tmp174, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HalfElf = tmp174 != 0
	tmp175, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Halfling = tmp175 != 0
	tmp176, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Human = tmp176 != 0
	tmp177, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Gnome = tmp177 != 0
	tmp178, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Monk = tmp178 != 0
	tmp179, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Druid = tmp179 != 0
	tmp180, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HalfOrc = tmp180 != 0
	return err
}
