// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"io"
)


/**
 * This file format acts as a central reference point to locate files required by the game (in a BIFF file on a CD or in
 * the `override` directory). The key file also maintains a mapping from an 8 byte resource name (refref) to a 32 byte ID
 * (using the lowest 12 bits to identify a resource). There is generally only one key file with each game (`chitin.key`).
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/key_v1.htm
 * ">Source</a>
 */

type Key_ResType int
const (
	Key_ResType__Bmp Key_ResType = 1
	Key_ResType__Mve Key_ResType = 2
	Key_ResType__Wav Key_ResType = 4
	Key_ResType__Wfx Key_ResType = 5
	Key_ResType__Plt Key_ResType = 6
	Key_ResType__Tga Key_ResType = 952
	Key_ResType__Bam Key_ResType = 1000
	Key_ResType__Wed Key_ResType = 1001
	Key_ResType__Chu Key_ResType = 1002
	Key_ResType__Tis Key_ResType = 1003
	Key_ResType__Mos Key_ResType = 1004
	Key_ResType__Itm Key_ResType = 1005
	Key_ResType__Spl Key_ResType = 1006
	Key_ResType__Bcs Key_ResType = 1007
	Key_ResType__Ids Key_ResType = 1008
	Key_ResType__Cre Key_ResType = 1009
	Key_ResType__Are Key_ResType = 1010
	Key_ResType__Dlg Key_ResType = 1011
	Key_ResType__TwoDa Key_ResType = 1012
	Key_ResType__Gam Key_ResType = 1013
	Key_ResType__Sto Key_ResType = 1014
	Key_ResType__Wmp Key_ResType = 1015
	Key_ResType__Eff Key_ResType = 1016
	Key_ResType__Bs Key_ResType = 1017
	Key_ResType__Chr Key_ResType = 1018
	Key_ResType__Vvc Key_ResType = 1019
	Key_ResType__Vef Key_ResType = 1020
	Key_ResType__Pro Key_ResType = 1021
	Key_ResType__Bio Key_ResType = 1022
	Key_ResType__Wbm Key_ResType = 1023
	Key_ResType__Fnt Key_ResType = 1024
	Key_ResType__Gui Key_ResType = 1026
	Key_ResType__Sql Key_ResType = 1027
	Key_ResType__Pvrz Key_ResType = 1028
	Key_ResType__Glsl Key_ResType = 1029
	Key_ResType__Tot Key_ResType = 1030
	Key_ResType__Toh Key_ResType = 1031
	Key_ResType__Menu Key_ResType = 1032
	Key_ResType__Lua Key_ResType = 1033
	Key_ResType__Ttf Key_ResType = 1034
	Key_ResType__Png Key_ResType = 1035
	Key_ResType__Bah Key_ResType = 1100
	Key_ResType__Ini Key_ResType = 2050
	Key_ResType__Src Key_ResType = 2051
	Key_ResType__Maze Key_ResType = 2052
	Key_ResType__Mus Key_ResType = 4094
	Key_ResType__Acm Key_ResType = 4095
)
var values_Key_ResType = map[Key_ResType]struct{}{1: {}, 2: {}, 4: {}, 5: {}, 6: {}, 952: {}, 1000: {}, 1001: {}, 1002: {}, 1003: {}, 1004: {}, 1005: {}, 1006: {}, 1007: {}, 1008: {}, 1009: {}, 1010: {}, 1011: {}, 1012: {}, 1013: {}, 1014: {}, 1015: {}, 1016: {}, 1017: {}, 1018: {}, 1019: {}, 1020: {}, 1021: {}, 1022: {}, 1023: {}, 1024: {}, 1026: {}, 1027: {}, 1028: {}, 1029: {}, 1030: {}, 1031: {}, 1032: {}, 1033: {}, 1034: {}, 1035: {}, 1100: {}, 2050: {}, 2051: {}, 2052: {}, 4094: {}, 4095: {}}
func (v Key_ResType) isDefined() bool {
	_, ok := values_Key_ResType[v]
	return ok
}
type Key struct {
	Magic []byte
	Version []byte
	NumBiffEntries uint32
	NumResEntries uint32
	OfsBiffEntries uint32
	OfsResEntries uint32
	_io *kaitai.Stream
	_root *Key
	_parent kaitai.Struct
	_f_biffEntries bool
	biffEntries []*Key_BiffEntry
	_f_resEntries bool
	resEntries []*Key_ResEntry
}
func NewKey() *Key {
	return &Key{
	}
}

func (this Key) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key) Read(io *kaitai.Stream, parent kaitai.Struct, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{75, 69, 89, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{75, 69, 89, 32}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = tmp2
	if !(bytes.Equal(this.Version, []uint8{86, 49, 32, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{86, 49, 32, 32}, this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumBiffEntries = uint32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumResEntries = uint32(tmp4)
	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsBiffEntries = uint32(tmp5)
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsResEntries = uint32(tmp6)
	return err
}
func (this *Key) BiffEntries() (v []*Key_BiffEntry, err error) {
	if (this._f_biffEntries) {
		return this.biffEntries, nil
	}
	this._f_biffEntries = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsBiffEntries), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumBiffEntries); i++ {
		_ = i
		tmp7 := NewKey_BiffEntry()
		err = tmp7.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.biffEntries = append(this.biffEntries, tmp7)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.biffEntries, nil
}
func (this *Key) ResEntries() (v []*Key_ResEntry, err error) {
	if (this._f_resEntries) {
		return this.resEntries, nil
	}
	this._f_resEntries = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this._root.OfsResEntries), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumResEntries); i++ {
		_ = i
		tmp8 := NewKey_ResEntry()
		err = tmp8.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.resEntries = append(this.resEntries, tmp8)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.resEntries, nil
}
type Key_BiffEntry struct {
	LenFile uint32
	OfsFilePath uint32
	LenFilePath uint16
	LocationBits *Key_BiffEntry_Location
	_io *kaitai.Stream
	_root *Key
	_parent kaitai.Struct
	_raw_LocationBits []byte
	_f_filePath bool
	filePath string
}
func NewKey_BiffEntry() *Key_BiffEntry {
	return &Key_BiffEntry{
	}
}

func (this Key_BiffEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_BiffEntry) Read(io *kaitai.Stream, parent kaitai.Struct, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp9, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenFile = uint32(tmp9)
	tmp10, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsFilePath = uint32(tmp10)
	tmp11, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenFilePath = uint16(tmp11)
	tmp12, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp12 = tmp12
	this._raw_LocationBits = tmp12
	_io__raw_LocationBits := kaitai.NewStream(bytes.NewReader(this._raw_LocationBits))
	tmp13 := NewKey_BiffEntry_Location()
	err = tmp13.Read(_io__raw_LocationBits, this, this._root)
	if err != nil {
		return err
	}
	this.LocationBits = tmp13
	return err
}
func (this *Key_BiffEntry) FilePath() (v string, err error) {
	if (this._f_filePath) {
		return this.filePath, nil
	}
	this._f_filePath = true
	thisIo := this._root._io
	_pos, err := thisIo.Pos()
	if err != nil {
		return "", err
	}
	_, err = thisIo.Seek(int64(this.OfsFilePath), io.SeekStart)
	if err != nil {
		return "", err
	}
	tmp14, err := thisIo.ReadBytes(int(this.LenFilePath))
	if err != nil {
		return "", err
	}
	tmp14 = kaitai.BytesTerminate(tmp14, 0, false)
	this.filePath = string(tmp14)
	_, err = thisIo.Seek(_pos, io.SeekStart)
	if err != nil {
		return "", err
	}
	return this.filePath, nil
}
type Key_BiffEntry_Location struct {
	InData bool
	InCache bool
	Cd []bool
	_io *kaitai.Stream
	_root *Key
	_parent *Key_BiffEntry
}
func NewKey_BiffEntry_Location() *Key_BiffEntry_Location {
	return &Key_BiffEntry_Location{
	}
}

func (this Key_BiffEntry_Location) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_BiffEntry_Location) Read(io *kaitai.Stream, parent *Key_BiffEntry, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp15, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.InData = tmp15 != 0
	tmp16, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.InCache = tmp16 != 0
	for i := 0; i < int(6); i++ {
		_ = i
		tmp17, err := this._io.ReadBitsIntLe(1)
		if err != nil {
			return err
		}
		this.Cd = append(this.Cd, tmp17 != 0)
	}
	return err
}
type Key_ResEntry struct {
	Name string
	Type Key_ResType
	Locator *Key_ResEntry_Locator
	_io *kaitai.Stream
	_root *Key
	_parent *Key
}
func NewKey_ResEntry() *Key_ResEntry {
	return &Key_ResEntry{
	}
}

func (this Key_ResEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_ResEntry) Read(io *kaitai.Stream, parent *Key, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp18, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp18 = kaitai.BytesTerminate(tmp18, 0, false)
	this.Name = string(tmp18)
	tmp19, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Type = Key_ResType(tmp19)
	tmp20 := NewKey_ResEntry_Locator(false)
	err = tmp20.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Locator = tmp20
	return err
}
type Key_ResEntry_Locator struct {
	FileIndex uint64
	TilesetIndex uint64
	BiffFileIndex uint64
	InBiff bool
	_io *kaitai.Stream
	_root *Key
	_parent *Key_ResEntry
	_f_biffFile bool
	biffFile *Key_BiffEntry
}
func NewKey_ResEntry_Locator(inBiff bool) *Key_ResEntry_Locator {
	return &Key_ResEntry_Locator{
		InBiff: inBiff,
	}
}

func (this Key_ResEntry_Locator) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_ResEntry_Locator) Read(io *kaitai.Stream, parent *Key_ResEntry, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp21, err := this._io.ReadBitsIntLe(14)
	if err != nil {
		return err
	}
	this.FileIndex = tmp21
	tmp22, err := this._io.ReadBitsIntLe(6)
	if err != nil {
		return err
	}
	this.TilesetIndex = tmp22
	tmp23, err := this._io.ReadBitsIntLe(12)
	if err != nil {
		return err
	}
	this.BiffFileIndex = tmp23
	return err
}
func (this *Key_ResEntry_Locator) BiffFile() (v *Key_BiffEntry, err error) {
	if (this._f_biffFile) {
		return this.biffFile, nil
	}
	this._f_biffFile = true
	if (!(this.InBiff)) {
		thisIo := this._root._io
		_pos, err := thisIo.Pos()
		if err != nil {
			return nil, err
		}
		_, err = thisIo.Seek(int64(uint64(this._root.OfsBiffEntries) + this.BiffFileIndex * 12), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp24 := NewKey_BiffEntry()
		err = tmp24.Read(thisIo, this, this._root)
		if err != nil {
			return nil, err
		}
		this.biffFile = tmp24
		_, err = thisIo.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.biffFile, nil
}
