// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)


/**
 * This file format describes projectiles, and the files are referenced spells and projectile weapons.
 * Projectile files can control:
 * 
 * - Projectile graphics
 * - Projectile speed
 * - Projectile area of effect
 * - Projectile sound
 * 
 * These files have constant length 256 bytes (no BAM), 512 bytes (single target), or 768 bytes (area of effect).
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/pro_v1.htm
 * ">Source</a>
 */

type Pro_ProjectileType int
const (
	Pro_ProjectileType__NoProjectile Pro_ProjectileType = 0
	Pro_ProjectileType__NoBam Pro_ProjectileType = 1
	Pro_ProjectileType__SingleTarget Pro_ProjectileType = 2
	Pro_ProjectileType__AreaOfEffect Pro_ProjectileType = 3
)
var values_Pro_ProjectileType = map[Pro_ProjectileType]struct{}{0: {}, 1: {}, 2: {}, 3: {}}
func (v Pro_ProjectileType) isDefined() bool {
	_, ok := values_Pro_ProjectileType[v]
	return ok
}
type Pro struct {
	Magic []byte
	Version []byte
	ProjectileType Pro_ProjectileType
	Speed uint16
	Flags *Pro_Flags
	FireSoundWav string
	ImpactSoundWav string
	SourceAnimation string
	ParticleColor uint16
	ProjectileWidth uint16
	ExtendedFlags *Pro_ExtendedFlags
	MessageRef uint32
	PulseColor *Pro_RgbaColor
	ColorSpeed uint16
	ScreenShakeAmount uint16
	_unnamed15 []byte
	IdsTarget1 uint16
	_unnamed17 []byte
	IdsTarget2 uint16
	DefaultSpellSpl string
	SuccessSpellSpl string
	PstAngleIncreaseMinimum uint16
	PstAngleIncreaseMaximum uint16
	PstCurveMinimum uint16
	PstCurveMaximum uint16
	PstThac0Bonus uint16
	PstThac0BonusNonActor uint16
	PstRadiusMinimum uint16
	PstRadiusMaximum uint16
	_unnamed29 []byte
	ProjectileInfo *Pro_ProjectileInfo
	AreaEffectInfo *Pro_AreaEffectInfo
	_io *kaitai.Stream
	_root *Pro
	_parent kaitai.Struct
	_raw_Flags []byte
	_raw_ExtendedFlags []byte
}
func NewPro() *Pro {
	return &Pro{
	}
}

func (this Pro) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro) Read(io *kaitai.Stream, parent kaitai.Struct, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{80, 82, 79, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{80, 82, 79, 32}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = tmp2
	if !(bytes.Equal(this.Version, []uint8{86, 49, 46, 48})) {
		return kaitai.NewValidationNotEqualError([]uint8{86, 49, 46, 48}, this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ProjectileType = Pro_ProjectileType(tmp3)
	tmp4, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Speed = uint16(tmp4)
	tmp5, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp5 = tmp5
	this._raw_Flags = tmp5
	_io__raw_Flags := kaitai.NewStream(bytes.NewReader(this._raw_Flags))
	tmp6 := NewPro_Flags()
	err = tmp6.Read(_io__raw_Flags, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp6
	tmp7, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp7 = kaitai.BytesTerminate(tmp7, 0, false)
	this.FireSoundWav = string(tmp7)
	tmp8, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp8 = kaitai.BytesTerminate(tmp8, 0, false)
	this.ImpactSoundWav = string(tmp8)
	tmp9, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp9 = kaitai.BytesTerminate(tmp9, 0, false)
	this.SourceAnimation = string(tmp9)
	tmp10, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ParticleColor = uint16(tmp10)
	tmp11, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ProjectileWidth = uint16(tmp11)
	tmp12, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp12 = tmp12
	this._raw_ExtendedFlags = tmp12
	_io__raw_ExtendedFlags := kaitai.NewStream(bytes.NewReader(this._raw_ExtendedFlags))
	tmp13 := NewPro_ExtendedFlags()
	err = tmp13.Read(_io__raw_ExtendedFlags, this, this._root)
	if err != nil {
		return err
	}
	this.ExtendedFlags = tmp13
	tmp14, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.MessageRef = uint32(tmp14)
	tmp15 := NewPro_RgbaColor()
	err = tmp15.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PulseColor = tmp15
	tmp16, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ColorSpeed = uint16(tmp16)
	tmp17, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ScreenShakeAmount = uint16(tmp17)
	tmp18, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp18 = tmp18
	this._unnamed15 = tmp18
	tmp19, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.IdsTarget1 = uint16(tmp19)
	tmp20, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp20 = tmp20
	this._unnamed17 = tmp20
	tmp21, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.IdsTarget2 = uint16(tmp21)
	tmp22, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp22 = kaitai.BytesTerminate(tmp22, 0, false)
	this.DefaultSpellSpl = string(tmp22)
	tmp23, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp23 = kaitai.BytesTerminate(tmp23, 0, false)
	this.SuccessSpellSpl = string(tmp23)
	tmp24, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PstAngleIncreaseMinimum = uint16(tmp24)
	tmp25, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PstAngleIncreaseMaximum = uint16(tmp25)
	tmp26, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PstCurveMinimum = uint16(tmp26)
	tmp27, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PstCurveMaximum = uint16(tmp27)
	tmp28, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PstThac0Bonus = uint16(tmp28)
	tmp29, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PstThac0BonusNonActor = uint16(tmp29)
	tmp30, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PstRadiusMinimum = uint16(tmp30)
	tmp31, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.PstRadiusMaximum = uint16(tmp31)
	tmp32, err := this._io.ReadBytes(int(156))
	if err != nil {
		return err
	}
	tmp32 = tmp32
	this._unnamed29 = tmp32
	if ( ((this.ProjectileType == Pro_ProjectileType__SingleTarget) || (this.ProjectileType == Pro_ProjectileType__AreaOfEffect)) ) {
		tmp33 := NewPro_ProjectileInfo()
		err = tmp33.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.ProjectileInfo = tmp33
	}
	if (this.ProjectileType == Pro_ProjectileType__AreaOfEffect) {
		tmp34 := NewPro_AreaEffectInfo()
		err = tmp34.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.AreaEffectInfo = tmp34
	}
	return err
}

/**
 * VEF > VVC > BAM
 */

/**
 * See `SPRKCLR.2DA`.
 */
type Pro_AreaEffectInfo struct {
	Flags *Pro_AreaEffectInfo_Flags
	RayCount uint16
	TrapSize uint16
	ExplosionSize uint16
	ExplosionSoundWav string
	ExplosionFrequency uint16
	FragmentAnimation uint16
	SecondaryProjectile uint16
	NumRepetitions uint8
	ExplosionEffect uint8
	ExplosionColor uint8
	_unnamed11 []byte
	ExplosionProjectile uint16
	ExplosionAnimation string
	ConeWidth uint16
	RotateRaysClockwise uint16
	SpreadAnimation string
	RingAnimation string
	AreaSoundWav string
	ExtendedFlags *Pro_AreaEffectInfo_ExtendedFlags
	NumDiceForMultipleTargets uint16
	DiceSizeForMultipleTargets uint16
	AnimationGranularity uint16
	AnimationGranularityDivider uint16
	_unnamed24 []byte
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro
	_raw_Flags []byte
	_raw_ExtendedFlags []byte
}
func NewPro_AreaEffectInfo() *Pro_AreaEffectInfo {
	return &Pro_AreaEffectInfo{
	}
}

func (this Pro_AreaEffectInfo) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_AreaEffectInfo) Read(io *kaitai.Stream, parent *Pro, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp35, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp35 = tmp35
	this._raw_Flags = tmp35
	_io__raw_Flags := kaitai.NewStream(bytes.NewReader(this._raw_Flags))
	tmp36 := NewPro_AreaEffectInfo_Flags()
	err = tmp36.Read(_io__raw_Flags, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp36
	tmp37, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.RayCount = uint16(tmp37)
	tmp38, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.TrapSize = uint16(tmp38)
	tmp39, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ExplosionSize = uint16(tmp39)
	tmp40, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp40 = kaitai.BytesTerminate(tmp40, 0, false)
	this.ExplosionSoundWav = string(tmp40)
	tmp41, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ExplosionFrequency = uint16(tmp41)
	tmp42, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.FragmentAnimation = uint16(tmp42)
	tmp43, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.SecondaryProjectile = uint16(tmp43)
	tmp44, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumRepetitions = tmp44
	tmp45, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ExplosionEffect = tmp45
	tmp46, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ExplosionColor = tmp46
	tmp47, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp47 = tmp47
	this._unnamed11 = tmp47
	tmp48, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ExplosionProjectile = uint16(tmp48)
	tmp49, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp49 = kaitai.BytesTerminate(tmp49, 0, false)
	this.ExplosionAnimation = string(tmp49)
	tmp50, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ConeWidth = uint16(tmp50)
	tmp51, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.RotateRaysClockwise = uint16(tmp51)
	tmp52, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp52 = kaitai.BytesTerminate(tmp52, 0, false)
	this.SpreadAnimation = string(tmp52)
	tmp53, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp53 = kaitai.BytesTerminate(tmp53, 0, false)
	this.RingAnimation = string(tmp53)
	tmp54, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp54 = kaitai.BytesTerminate(tmp54, 0, false)
	this.AreaSoundWav = string(tmp54)
	tmp55, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp55 = tmp55
	this._raw_ExtendedFlags = tmp55
	_io__raw_ExtendedFlags := kaitai.NewStream(bytes.NewReader(this._raw_ExtendedFlags))
	tmp56 := NewPro_AreaEffectInfo_ExtendedFlags()
	err = tmp56.Read(_io__raw_ExtendedFlags, this, this._root)
	if err != nil {
		return err
	}
	this.ExtendedFlags = tmp56
	tmp57, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumDiceForMultipleTargets = uint16(tmp57)
	tmp58, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.DiceSizeForMultipleTargets = uint16(tmp58)
	tmp59, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.AnimationGranularity = uint16(tmp59)
	tmp60, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.AnimationGranularityDivider = uint16(tmp60)
	tmp61, err := this._io.ReadBytes(int(180))
	if err != nil {
		return err
	}
	tmp61 = tmp61
	this._unnamed24 = tmp61
	return err
}

/**
 * See `ANIMATE.IDS`.
 */

/**
 * See `PROJECTL.IDS`.
 */

/**
 * See `FIREBALL.IDS`.
 */

/**
 * See `PROJECTL.IDS`.
 */
type Pro_AreaEffectInfo_ExtendedFlags struct {
	PalettedRing bool
	RandomSpeed bool
	StartScattered bool
	PalettedCenter bool
	RepeatScattering bool
	PalettedAnimation bool
	_unnamed6 uint64
	OrientedFireballPuffs bool
	UseHitDiceLookup bool
	_unnamed9 uint64
	BlendAreaRingAnimation bool
	GlowAreaRingAnimation bool
	HitPointLimit bool
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro_AreaEffectInfo
}
func NewPro_AreaEffectInfo_ExtendedFlags() *Pro_AreaEffectInfo_ExtendedFlags {
	return &Pro_AreaEffectInfo_ExtendedFlags{
	}
}

func (this Pro_AreaEffectInfo_ExtendedFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_AreaEffectInfo_ExtendedFlags) Read(io *kaitai.Stream, parent *Pro_AreaEffectInfo, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp62, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PalettedRing = tmp62 != 0
	tmp63, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.RandomSpeed = tmp63 != 0
	tmp64, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.StartScattered = tmp64 != 0
	tmp65, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PalettedCenter = tmp65 != 0
	tmp66, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.RepeatScattering = tmp66 != 0
	tmp67, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PalettedAnimation = tmp67 != 0
	tmp68, err := this._io.ReadBitsIntLe(3)
	if err != nil {
		return err
	}
	this._unnamed6 = tmp68
	tmp69, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.OrientedFireballPuffs = tmp69 != 0
	tmp70, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UseHitDiceLookup = tmp70 != 0
	tmp71, err := this._io.ReadBitsIntLe(2)
	if err != nil {
		return err
	}
	this._unnamed9 = tmp71
	tmp72, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BlendAreaRingAnimation = tmp72 != 0
	tmp73, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.GlowAreaRingAnimation = tmp73 != 0
	tmp74, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HitPointLimit = tmp74 != 0
	return err
}
type Pro_AreaEffectInfo_Flags struct {
	TrapVisible bool
	TriggeredByInanimateObjects bool
	TriggeredByCondition bool
	DelayedTrigger bool
	UseSecondaryProjectile bool
	UseFragmentGraphics bool
	AffectOnlyEnemies bool
	AffectOnlyAllies bool
	MageLevelDuration bool
	ClericLevelDuration bool
	DrawAnimation bool
	ConeShaped bool
	IgnoreLos bool
	DelayedExplosion bool
	SkipFirstCondition bool
	SingleTarget bool
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro_AreaEffectInfo
}
func NewPro_AreaEffectInfo_Flags() *Pro_AreaEffectInfo_Flags {
	return &Pro_AreaEffectInfo_Flags{
	}
}

func (this Pro_AreaEffectInfo_Flags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_AreaEffectInfo_Flags) Read(io *kaitai.Stream, parent *Pro_AreaEffectInfo, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp75, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TrapVisible = tmp75 != 0
	tmp76, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TriggeredByInanimateObjects = tmp76 != 0
	tmp77, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TriggeredByCondition = tmp77 != 0
	tmp78, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DelayedTrigger = tmp78 != 0
	tmp79, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UseSecondaryProjectile = tmp79 != 0
	tmp80, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UseFragmentGraphics = tmp80 != 0
	tmp81, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AffectOnlyEnemies = tmp81 != 0
	tmp82, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AffectOnlyAllies = tmp82 != 0
	tmp83, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.MageLevelDuration = tmp83 != 0
	tmp84, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericLevelDuration = tmp84 != 0
	tmp85, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DrawAnimation = tmp85 != 0
	tmp86, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ConeShaped = tmp86 != 0
	tmp87, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgnoreLos = tmp87 != 0
	tmp88, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DelayedExplosion = tmp88 != 0
	tmp89, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.SkipFirstCondition = tmp89 != 0
	tmp90, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.SingleTarget = tmp90 != 0
	return err
}
type Pro_ExtendedFlags struct {
	BounceFromWalls bool
	PassTarget bool
	DrawCenterVvcOnce bool
	HitImmemdiately bool
	FaceTarget bool
	CurvedPath bool
	StartRandomFrame bool
	Pillar bool
	SemiTransparentTrailPuffVef bool
	TintedTrailPuffVef bool
	MultipleProjectiles bool
	DefaultSpellOnMissed bool
	FallingPath bool
	Comet bool
	LinedUpAoe bool
	RectangularAoe bool
	DrawBehindTarget bool
	CasingFlowEffect bool
	TravelDoor bool
	StopFadeAfterHit bool
	DisplayMessage bool
	RandomPath bool
	StartRandomSequence bool
	ColorPulseOnHit bool
	TouchProjectile bool
	NegateIds1 bool
	NegateIds2 bool
	UseEitherIds bool
	DelayedPayload bool
	LimitedPathCount bool
	IwdStyleCheck bool
	CasterAffected bool
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro
}
func NewPro_ExtendedFlags() *Pro_ExtendedFlags {
	return &Pro_ExtendedFlags{
	}
}

func (this Pro_ExtendedFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_ExtendedFlags) Read(io *kaitai.Stream, parent *Pro, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp91, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BounceFromWalls = tmp91 != 0
	tmp92, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PassTarget = tmp92 != 0
	tmp93, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DrawCenterVvcOnce = tmp93 != 0
	tmp94, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HitImmemdiately = tmp94 != 0
	tmp95, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FaceTarget = tmp95 != 0
	tmp96, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CurvedPath = tmp96 != 0
	tmp97, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.StartRandomFrame = tmp97 != 0
	tmp98, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Pillar = tmp98 != 0
	tmp99, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.SemiTransparentTrailPuffVef = tmp99 != 0
	tmp100, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TintedTrailPuffVef = tmp100 != 0
	tmp101, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.MultipleProjectiles = tmp101 != 0
	tmp102, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DefaultSpellOnMissed = tmp102 != 0
	tmp103, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.FallingPath = tmp103 != 0
	tmp104, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Comet = tmp104 != 0
	tmp105, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LinedUpAoe = tmp105 != 0
	tmp106, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.RectangularAoe = tmp106 != 0
	tmp107, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DrawBehindTarget = tmp107 != 0
	tmp108, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CasingFlowEffect = tmp108 != 0
	tmp109, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TravelDoor = tmp109 != 0
	tmp110, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.StopFadeAfterHit = tmp110 != 0
	tmp111, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DisplayMessage = tmp111 != 0
	tmp112, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.RandomPath = tmp112 != 0
	tmp113, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.StartRandomSequence = tmp113 != 0
	tmp114, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ColorPulseOnHit = tmp114 != 0
	tmp115, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TouchProjectile = tmp115 != 0
	tmp116, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NegateIds1 = tmp116 != 0
	tmp117, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NegateIds2 = tmp117 != 0
	tmp118, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UseEitherIds = tmp118 != 0
	tmp119, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DelayedPayload = tmp119 != 0
	tmp120, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LimitedPathCount = tmp120 != 0
	tmp121, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IwdStyleCheck = tmp121 != 0
	tmp122, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CasterAffected = tmp122 != 0
	return err
}
type Pro_Flags struct {
	ShowSparkle bool
	UseHeight bool
	LoopFireSound bool
	LoopImpactSound bool
	IgnoreCenter bool
	DrawAsBackground bool
	AllowSaving bool
	LoopSpreadAnimation bool
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro
}
func NewPro_Flags() *Pro_Flags {
	return &Pro_Flags{
	}
}

func (this Pro_Flags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_Flags) Read(io *kaitai.Stream, parent *Pro, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp123, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ShowSparkle = tmp123 != 0
	tmp124, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UseHeight = tmp124 != 0
	tmp125, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LoopFireSound = tmp125 != 0
	tmp126, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LoopImpactSound = tmp126 != 0
	tmp127, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgnoreCenter = tmp127 != 0
	tmp128, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DrawAsBackground = tmp128 != 0
	tmp129, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AllowSaving = tmp129 != 0
	tmp130, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LoopSpreadAnimation = tmp130 != 0
	return err
}

type Pro_ProjectileInfo_GranularityMirroring int
const (
	Pro_ProjectileInfo_GranularityMirroring__DoNotMirror Pro_ProjectileInfo_GranularityMirroring = 0
	Pro_ProjectileInfo_GranularityMirroring__DoNotFaceTarget Pro_ProjectileInfo_GranularityMirroring = 1
	Pro_ProjectileInfo_GranularityMirroring__MirroredEastReduced Pro_ProjectileInfo_GranularityMirroring = 5
	Pro_ProjectileInfo_GranularityMirroring__MirroredEastFull Pro_ProjectileInfo_GranularityMirroring = 9
	Pro_ProjectileInfo_GranularityMirroring__NotMirroredFull Pro_ProjectileInfo_GranularityMirroring = 16
)
var values_Pro_ProjectileInfo_GranularityMirroring = map[Pro_ProjectileInfo_GranularityMirroring]struct{}{0: {}, 1: {}, 5: {}, 9: {}, 16: {}}
func (v Pro_ProjectileInfo_GranularityMirroring) isDefined() bool {
	_, ok := values_Pro_ProjectileInfo_GranularityMirroring[v]
	return ok
}
type Pro_ProjectileInfo struct {
	Flags *Pro_ProjectileInfo_Flags
	ProjectileAnimationBam string
	ShadowAnimationBam string
	ProjectileAnimationNumber uint8
	ShadowAnimationNumber uint8
	LightSpotIntensity uint16
	LightSpotWidth uint16
	LightSpotHeight uint16
	PaletteBmp string
	ProjectileColors []uint8
	SmokePuffDelay uint8
	SmokeColors []uint8
	FaceTargetGranularityMirroring Pro_ProjectileInfo_GranularityMirroring
	SmokeAnimation uint16
	TrailingAnimationsBam []string
	TrailingAnimationDelays []uint16
	TrailFlags *Pro_ProjectileInfo_TrailFlags
	_unnamed17 []byte
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro
	_raw_Flags []byte
	_raw_TrailFlags []byte
}
func NewPro_ProjectileInfo() *Pro_ProjectileInfo {
	return &Pro_ProjectileInfo{
	}
}

func (this Pro_ProjectileInfo) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_ProjectileInfo) Read(io *kaitai.Stream, parent *Pro, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp131, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp131 = tmp131
	this._raw_Flags = tmp131
	_io__raw_Flags := kaitai.NewStream(bytes.NewReader(this._raw_Flags))
	tmp132 := NewPro_ProjectileInfo_Flags()
	err = tmp132.Read(_io__raw_Flags, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp132
	tmp133, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp133 = kaitai.BytesTerminate(tmp133, 0, false)
	this.ProjectileAnimationBam = string(tmp133)
	tmp134, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp134 = kaitai.BytesTerminate(tmp134, 0, false)
	this.ShadowAnimationBam = string(tmp134)
	tmp135, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ProjectileAnimationNumber = tmp135
	tmp136, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ShadowAnimationNumber = tmp136
	tmp137, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LightSpotIntensity = uint16(tmp137)
	tmp138, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LightSpotWidth = uint16(tmp138)
	tmp139, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LightSpotHeight = uint16(tmp139)
	tmp140, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp140 = kaitai.BytesTerminate(tmp140, 0, false)
	this.PaletteBmp = string(tmp140)
	for i := 0; i < int(7); i++ {
		_ = i
		tmp141, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.ProjectileColors = append(this.ProjectileColors, tmp141)
	}
	tmp142, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SmokePuffDelay = tmp142
	for i := 0; i < int(7); i++ {
		_ = i
		tmp143, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.SmokeColors = append(this.SmokeColors, tmp143)
	}
	tmp144, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.FaceTargetGranularityMirroring = Pro_ProjectileInfo_GranularityMirroring(tmp144)
	tmp145, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.SmokeAnimation = uint16(tmp145)
	for i := 0; i < int(3); i++ {
		_ = i
		tmp146, err := this._io.ReadBytes(int(8))
		if err != nil {
			return err
		}
		tmp146 = kaitai.BytesTerminate(tmp146, 0, false)
		this.TrailingAnimationsBam = append(this.TrailingAnimationsBam, string(tmp146))
	}
	for i := 0; i < int(3); i++ {
		_ = i
		tmp147, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.TrailingAnimationDelays = append(this.TrailingAnimationDelays, tmp147)
	}
	tmp148, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp148 = tmp148
	this._raw_TrailFlags = tmp148
	_io__raw_TrailFlags := kaitai.NewStream(bytes.NewReader(this._raw_TrailFlags))
	tmp149 := NewPro_ProjectileInfo_TrailFlags()
	err = tmp149.Read(_io__raw_TrailFlags, this, this._root)
	if err != nil {
		return err
	}
	this.TrailFlags = tmp149
	tmp150, err := this._io.ReadBytes(int(168))
	if err != nil {
		return err
	}
	tmp150 = tmp150
	this._unnamed17 = tmp150
	return err
}

/**
 * See `ANIMATE.IDS`.
 */
type Pro_ProjectileInfo_Flags struct {
	EnableBamColoring bool
	CreateSmoke bool
	ColoredSmoke bool
	NotLightSource bool
	ModifyForHeight bool
	CastsShadows bool
	EnableLightSpot bool
	Translucent bool
	MidLevelBrighten bool
	Blended bool
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro_ProjectileInfo
}
func NewPro_ProjectileInfo_Flags() *Pro_ProjectileInfo_Flags {
	return &Pro_ProjectileInfo_Flags{
	}
}

func (this Pro_ProjectileInfo_Flags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_ProjectileInfo_Flags) Read(io *kaitai.Stream, parent *Pro_ProjectileInfo, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp151, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EnableBamColoring = tmp151 != 0
	tmp152, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CreateSmoke = tmp152 != 0
	tmp153, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ColoredSmoke = tmp153 != 0
	tmp154, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NotLightSource = tmp154 != 0
	tmp155, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ModifyForHeight = tmp155 != 0
	tmp156, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CastsShadows = tmp156 != 0
	tmp157, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.EnableLightSpot = tmp157 != 0
	tmp158, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Translucent = tmp158 != 0
	tmp159, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.MidLevelBrighten = tmp159 != 0
	tmp160, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Blended = tmp160 != 0
	return err
}
type Pro_ProjectileInfo_TrailFlags struct {
	PuffAtTarget bool
	PuffAtSource bool
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro_ProjectileInfo
}
func NewPro_ProjectileInfo_TrailFlags() *Pro_ProjectileInfo_TrailFlags {
	return &Pro_ProjectileInfo_TrailFlags{
	}
}

func (this Pro_ProjectileInfo_TrailFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_ProjectileInfo_TrailFlags) Read(io *kaitai.Stream, parent *Pro_ProjectileInfo, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp161, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PuffAtTarget = tmp161 != 0
	tmp162, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PuffAtSource = tmp162 != 0
	return err
}
type Pro_RgbaColor struct {
	Red uint8
	Green uint8
	Blue uint8
	Alpha uint8
	_io *kaitai.Stream
	_root *Pro
	_parent *Pro
}
func NewPro_RgbaColor() *Pro_RgbaColor {
	return &Pro_RgbaColor{
	}
}

func (this Pro_RgbaColor) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pro_RgbaColor) Read(io *kaitai.Stream, parent *Pro, root *Pro) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp163, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Red = tmp163
	tmp164, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Green = tmp164
	tmp165, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Blue = tmp165
	tmp166, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Alpha = tmp166
	return err
}
