// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"io"
)


/**
 * This file format describes a "spell". Spells include mage spells, priest spells, innate abilities, special abilities
 * and effects used for game advancement (e.g. animation effects, custom spells).
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/spl_v1.htm
 * ">Source</a>
 */

type Spl_SpellType int
const (
	Spl_SpellType__Special Spl_SpellType = 0
	Spl_SpellType__Wizard Spl_SpellType = 1
	Spl_SpellType__Priest Spl_SpellType = 2
	Spl_SpellType__Psionic Spl_SpellType = 3
	Spl_SpellType__Innate Spl_SpellType = 4
	Spl_SpellType__BardSong Spl_SpellType = 5
)
var values_Spl_SpellType = map[Spl_SpellType]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}}
func (v Spl_SpellType) isDefined() bool {
	_, ok := values_Spl_SpellType[v]
	return ok
}
type Spl struct {
	Magic []byte
	Version []byte
	UnidentifiedNameRef uint32
	IdentifiedNameRef uint32
	CastingSoundWav string
	Flags *Spl_Flags
	SpellType Spl_SpellType
	ExclusionFlags kaitai.Struct
	CastingAnimation uint16
	_unnamed9 []byte
	PrimarySchool uint8
	MinStrength uint8
	SecondaryType uint8
	_unnamed13 []byte
	SpellLevel uint32
	_unnamed15 []byte
	SpellbookIconBam string
	_unnamed17 []byte
	_unnamed18 []byte
	_unnamed19 []byte
	UnidentifiedDescriptionRef uint32
	IdentifiedDescriptionRef uint32
	DescriptionIconBam string
	_unnamed23 []byte
	OfsExtendedHeaders uint32
	NumExtendedHeaders uint16
	OfsEffects uint32
	FirstEffectIndex uint16
	NumEffects uint16
	_io *kaitai.Stream
	_root *Spl
	_parent kaitai.Struct
	_raw_Flags []byte
	_raw_ExclusionFlags []byte
	_raw_effects [][]byte
	_raw_extendedHeaders [][]byte
	_f_effects bool
	effects []*Eff_BodyV1
	_f_extendedHeaders bool
	extendedHeaders []*Spl_ExtendedHeader
}
func NewSpl() *Spl {
	return &Spl{
	}
}

func (this Spl) IO_() *kaitai.Stream {
	return this._io
}

func (this *Spl) Read(io *kaitai.Stream, parent kaitai.Struct, root *Spl) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{83, 80, 76, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{83, 80, 76, 32}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = tmp2
	if !(bytes.Equal(this.Version, []uint8{86, 49, 32, 32})) {
		return kaitai.NewValidationNotEqualError([]uint8{86, 49, 32, 32}, this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.UnidentifiedNameRef = uint32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IdentifiedNameRef = uint32(tmp4)
	tmp5, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp5 = kaitai.BytesTerminate(tmp5, 0, false)
	this.CastingSoundWav = string(tmp5)
	tmp6, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp6 = tmp6
	this._raw_Flags = tmp6
	_io__raw_Flags := kaitai.NewStream(bytes.NewReader(this._raw_Flags))
	tmp7 := NewSpl_Flags()
	err = tmp7.Read(_io__raw_Flags, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp7
	tmp8, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.SpellType = Spl_SpellType(tmp8)
	switch (this.SpellType) {
	case Spl_SpellType__Priest:
		tmp9, err := this._io.ReadBytes(int(4))
		if err != nil {
			return err
		}
		tmp9 = tmp9
		this._raw_ExclusionFlags = tmp9
		_io__raw_ExclusionFlags := kaitai.NewStream(bytes.NewReader(this._raw_ExclusionFlags))
		tmp10 := NewSpl_ExclusionFlagsPriest()
		err = tmp10.Read(_io__raw_ExclusionFlags, this, this._root)
		if err != nil {
			return err
		}
		this.ExclusionFlags = tmp10
	default:
		tmp11, err := this._io.ReadBytes(int(4))
		if err != nil {
			return err
		}
		tmp11 = tmp11
		this._raw_ExclusionFlags = tmp11
		_io__raw_ExclusionFlags := kaitai.NewStream(bytes.NewReader(this._raw_ExclusionFlags))
		tmp12 := NewSpl_ExclusionFlags()
		err = tmp12.Read(_io__raw_ExclusionFlags, this, this._root)
		if err != nil {
			return err
		}
		this.ExclusionFlags = tmp12
	}
	tmp13, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.CastingAnimation = uint16(tmp13)
	tmp14, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp14 = tmp14
	this._unnamed9 = tmp14
	tmp15, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.PrimarySchool = tmp15
	tmp16, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MinStrength = tmp16
	tmp17, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SecondaryType = tmp17
	tmp18, err := this._io.ReadBytes(int(12))
	if err != nil {
		return err
	}
	tmp18 = tmp18
	this._unnamed13 = tmp18
	tmp19, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SpellLevel = uint32(tmp19)
	tmp20, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp20 = tmp20
	this._unnamed15 = tmp20
	tmp21, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp21 = kaitai.BytesTerminate(tmp21, 0, false)
	this.SpellbookIconBam = string(tmp21)
	tmp22, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp22 = tmp22
	this._unnamed17 = tmp22
	tmp23, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp23 = tmp23
	this._unnamed18 = tmp23
	tmp24, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp24 = tmp24
	this._unnamed19 = tmp24
	tmp25, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.UnidentifiedDescriptionRef = uint32(tmp25)
	tmp26, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IdentifiedDescriptionRef = uint32(tmp26)
	tmp27, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp27 = kaitai.BytesTerminate(tmp27, 0, false)
	this.DescriptionIconBam = string(tmp27)
	tmp28, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp28 = tmp28
	this._unnamed23 = tmp28
	tmp29, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsExtendedHeaders = uint32(tmp29)
	tmp30, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumExtendedHeaders = uint16(tmp30)
	tmp31, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OfsEffects = uint32(tmp31)
	tmp32, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.FirstEffectIndex = uint16(tmp32)
	tmp33, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumEffects = uint16(tmp33)
	return err
}
func (this *Spl) Effects() (v []*Eff_BodyV1, err error) {
	if (this._f_effects) {
		return this.effects, nil
	}
	this._f_effects = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsEffects + uint32(this.FirstEffectIndex) * 48), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumEffects); i++ {
		_ = i
		tmp34, err := this._io.ReadBytes(int(48))
		if err != nil {
			return nil, err
		}
		tmp34 = tmp34
		this._raw_effects = append(this._raw_effects, tmp34)
		_io__raw_effects := kaitai.NewStream(bytes.NewReader(this._raw_effects[i]))
		tmp35 := NewEff_BodyV1()
		err = tmp35.Read(_io__raw_effects, nil, nil)
		if err != nil {
			return nil, err
		}
		this.effects = append(this.effects, tmp35)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.effects, nil
}
func (this *Spl) ExtendedHeaders() (v []*Spl_ExtendedHeader, err error) {
	if (this._f_extendedHeaders) {
		return this.extendedHeaders, nil
	}
	this._f_extendedHeaders = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OfsExtendedHeaders), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumExtendedHeaders); i++ {
		_ = i
		tmp36, err := this._io.ReadBytes(int(40))
		if err != nil {
			return nil, err
		}
		tmp36 = tmp36
		this._raw_extendedHeaders = append(this._raw_extendedHeaders, tmp36)
		_io__raw_extendedHeaders := kaitai.NewStream(bytes.NewReader(this._raw_extendedHeaders[i]))
		tmp37 := NewSpl_ExtendedHeader()
		err = tmp37.Read(_io__raw_extendedHeaders, this, this._root)
		if err != nil {
			return nil, err
		}
		this.extendedHeaders = append(this.extendedHeaders, tmp37)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.extendedHeaders, nil
}

/**
 * Unused.
 */

/**
 * See `school.2da`/`mschool.2da`.
 */

/**
 * See `msectype.2da`.
 */

/**
 * Unused.
 */

/**
 * Unused.
 */
type Spl_ExclusionFlags struct {
	Berserker bool
	WizardSlayer bool
	Kensai bool
	Cavalier bool
	Inquisitor bool
	UndeadHunter bool
	Abjurer bool
	Conjurer bool
	Diviner bool
	Enchanter bool
	Illusionist bool
	Invoker bool
	Necromancer bool
	Transmuter bool
	Generalist bool
	Archer bool
	Stalker bool
	Beastmaster bool
	Assassin bool
	BountyHunter bool
	Swashbuckler bool
	Blade bool
	Jester bool
	Skald bool
	ClericOfTalos bool
	ClericOfHelm bool
	ClericOfLathander bool
	TotemicDruid bool
	Shapeshifter bool
	Avenger bool
	Barbarian bool
	WildMage bool
	_io *kaitai.Stream
	_root *Spl
	_parent *Spl
}
func NewSpl_ExclusionFlags() *Spl_ExclusionFlags {
	return &Spl_ExclusionFlags{
	}
}

func (this Spl_ExclusionFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Spl_ExclusionFlags) Read(io *kaitai.Stream, parent *Spl, root *Spl) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp38, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Berserker = tmp38 != 0
	tmp39, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.WizardSlayer = tmp39 != 0
	tmp40, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Kensai = tmp40 != 0
	tmp41, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Cavalier = tmp41 != 0
	tmp42, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Inquisitor = tmp42 != 0
	tmp43, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UndeadHunter = tmp43 != 0
	tmp44, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Abjurer = tmp44 != 0
	tmp45, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Conjurer = tmp45 != 0
	tmp46, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Diviner = tmp46 != 0
	tmp47, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Enchanter = tmp47 != 0
	tmp48, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Illusionist = tmp48 != 0
	tmp49, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Invoker = tmp49 != 0
	tmp50, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Necromancer = tmp50 != 0
	tmp51, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Transmuter = tmp51 != 0
	tmp52, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Generalist = tmp52 != 0
	tmp53, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Archer = tmp53 != 0
	tmp54, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Stalker = tmp54 != 0
	tmp55, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Beastmaster = tmp55 != 0
	tmp56, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Assassin = tmp56 != 0
	tmp57, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BountyHunter = tmp57 != 0
	tmp58, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Swashbuckler = tmp58 != 0
	tmp59, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Blade = tmp59 != 0
	tmp60, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Jester = tmp60 != 0
	tmp61, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Skald = tmp61 != 0
	tmp62, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericOfTalos = tmp62 != 0
	tmp63, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericOfHelm = tmp63 != 0
	tmp64, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericOfLathander = tmp64 != 0
	tmp65, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TotemicDruid = tmp65 != 0
	tmp66, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Shapeshifter = tmp66 != 0
	tmp67, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Avenger = tmp67 != 0
	tmp68, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Barbarian = tmp68 != 0
	tmp69, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.WildMage = tmp69 != 0
	return err
}
type Spl_ExclusionFlagsPriest struct {
	ChaoticPrefix bool
	Evil bool
	Good bool
	Neutral bool
	LawfulPrefix bool
	NeutralPrefix bool
	_unnamed6 uint64
	ClericPaladin bool
	DruidRangerShaman bool
	_io *kaitai.Stream
	_root *Spl
	_parent *Spl
}
func NewSpl_ExclusionFlagsPriest() *Spl_ExclusionFlagsPriest {
	return &Spl_ExclusionFlagsPriest{
	}
}

func (this Spl_ExclusionFlagsPriest) IO_() *kaitai.Stream {
	return this._io
}

func (this *Spl_ExclusionFlagsPriest) Read(io *kaitai.Stream, parent *Spl, root *Spl) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp70, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ChaoticPrefix = tmp70 != 0
	tmp71, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Evil = tmp71 != 0
	tmp72, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Good = tmp72 != 0
	tmp73, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Neutral = tmp73 != 0
	tmp74, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LawfulPrefix = tmp74 != 0
	tmp75, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NeutralPrefix = tmp75 != 0
	tmp76, err := this._io.ReadBitsIntLe(24)
	if err != nil {
		return err
	}
	this._unnamed6 = tmp76
	tmp77, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.ClericPaladin = tmp77 != 0
	tmp78, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.DruidRangerShaman = tmp78 != 0
	return err
}

type Spl_ExtendedHeader_SpellForm int
const (
	Spl_ExtendedHeader_SpellForm__None Spl_ExtendedHeader_SpellForm = 0
	Spl_ExtendedHeader_SpellForm__Melee Spl_ExtendedHeader_SpellForm = 1
	Spl_ExtendedHeader_SpellForm__Ranged Spl_ExtendedHeader_SpellForm = 2
	Spl_ExtendedHeader_SpellForm__Magical Spl_ExtendedHeader_SpellForm = 3
	Spl_ExtendedHeader_SpellForm__Launcher Spl_ExtendedHeader_SpellForm = 4
)
var values_Spl_ExtendedHeader_SpellForm = map[Spl_ExtendedHeader_SpellForm]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}}
func (v Spl_ExtendedHeader_SpellForm) isDefined() bool {
	_, ok := values_Spl_ExtendedHeader_SpellForm[v]
	return ok
}
type Spl_ExtendedHeader struct {
	SpellForm Spl_ExtendedHeader_SpellForm
	TypeFlags *Spl_ExtendedHeader_TypeFlags
	Location Itm_Location
	IconBam string
	Target Itm_TargetType
	TargetCount uint8
	Range uint16
	MinimumLevel uint16
	CastingSpeed uint16
	TimesPerDay uint16
	_unnamed10 []byte
	NumEffects uint16
	FirstEffectIndex uint16
	_unnamed13 []byte
	ProjectilePro uint16
	_io *kaitai.Stream
	_root *Spl
	_parent *Spl
	_raw_TypeFlags []byte
	_raw_effects [][]byte
	_f_effects bool
	effects []*Eff_BodyV1
}
func NewSpl_ExtendedHeader() *Spl_ExtendedHeader {
	return &Spl_ExtendedHeader{
	}
}

func (this Spl_ExtendedHeader) IO_() *kaitai.Stream {
	return this._io
}

func (this *Spl_ExtendedHeader) Read(io *kaitai.Stream, parent *Spl, root *Spl) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp79, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SpellForm = Spl_ExtendedHeader_SpellForm(tmp79)
	tmp80, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp80 = tmp80
	this._raw_TypeFlags = tmp80
	_io__raw_TypeFlags := kaitai.NewStream(bytes.NewReader(this._raw_TypeFlags))
	tmp81 := NewSpl_ExtendedHeader_TypeFlags()
	err = tmp81.Read(_io__raw_TypeFlags, this, this._root)
	if err != nil {
		return err
	}
	this.TypeFlags = tmp81
	tmp82, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Location = Itm_Location(tmp82)
	tmp83, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp83 = kaitai.BytesTerminate(tmp83, 0, false)
	this.IconBam = string(tmp83)
	tmp84, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Target = Itm_TargetType(tmp84)
	tmp85, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TargetCount = tmp85
	tmp86, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Range = uint16(tmp86)
	tmp87, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.MinimumLevel = uint16(tmp87)
	tmp88, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.CastingSpeed = uint16(tmp88)
	tmp89, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.TimesPerDay = uint16(tmp89)
	tmp90, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp90 = tmp90
	this._unnamed10 = tmp90
	tmp91, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumEffects = uint16(tmp91)
	tmp92, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.FirstEffectIndex = uint16(tmp92)
	tmp93, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp93 = tmp93
	this._unnamed13 = tmp93
	tmp94, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ProjectilePro = uint16(tmp94)
	return err
}
func (this *Spl_ExtendedHeader) Effects() (v []*Eff_BodyV1, err error) {
	if (this._f_effects) {
		return this.effects, nil
	}
	this._f_effects = true
	thisIo := this._root._io
	_pos, err := thisIo.Pos()
	if err != nil {
		return nil, err
	}
	_, err = thisIo.Seek(int64(this._root.OfsEffects + uint32(this.FirstEffectIndex) * 48), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NumEffects); i++ {
		_ = i
		tmp95, err := thisIo.ReadBytes(int(48))
		if err != nil {
			return nil, err
		}
		tmp95 = tmp95
		this._raw_effects = append(this._raw_effects, tmp95)
		_io__raw_effects := kaitai.NewStream(bytes.NewReader(this._raw_effects[i]))
		tmp96 := NewEff_BodyV1()
		err = tmp96.Read(_io__raw_effects, nil, nil)
		if err != nil {
			return nil, err
		}
		this.effects = append(this.effects, tmp96)
	}
	_, err = thisIo.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.effects, nil
}

/**
 * See `projectl.ids`
 */
type Spl_ExtendedHeader_TypeFlags struct {
	UsableAfterId bool
	UsableBeforeId bool
	PstNonHostileProjectile bool
	_io *kaitai.Stream
	_root *Spl
	_parent *Spl_ExtendedHeader
}
func NewSpl_ExtendedHeader_TypeFlags() *Spl_ExtendedHeader_TypeFlags {
	return &Spl_ExtendedHeader_TypeFlags{
	}
}

func (this Spl_ExtendedHeader_TypeFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Spl_ExtendedHeader_TypeFlags) Read(io *kaitai.Stream, parent *Spl_ExtendedHeader, root *Spl) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp97, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UsableAfterId = tmp97 != 0
	tmp98, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.UsableBeforeId = tmp98 != 0
	tmp99, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.PstNonHostileProjectile = tmp99 != 0
	return err
}
type Spl_Flags struct {
	_unnamed0 uint64
	BreaksSanctuaryInvisibility bool
	Hostile bool
	NoLosRequired bool
	AllowSpotting bool
	OutdoorsOnly bool
	IgnoreDeadMagicAndWildSurgeEffect bool
	IgnoreWildSurgeEffect bool
	NotInCombat bool
	_unnamed9 uint64
	CanTargetInvisible bool
	CastableWhenSilenced bool
	_unnamed12 uint64
	_io *kaitai.Stream
	_root *Spl
	_parent *Spl
}
func NewSpl_Flags() *Spl_Flags {
	return &Spl_Flags{
	}
}

func (this Spl_Flags) IO_() *kaitai.Stream {
	return this._io
}

func (this *Spl_Flags) Read(io *kaitai.Stream, parent *Spl, root *Spl) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp100, err := this._io.ReadBitsIntLe(9)
	if err != nil {
		return err
	}
	this._unnamed0 = tmp100
	tmp101, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BreaksSanctuaryInvisibility = tmp101 != 0
	tmp102, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Hostile = tmp102 != 0
	tmp103, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NoLosRequired = tmp103 != 0
	tmp104, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AllowSpotting = tmp104 != 0
	tmp105, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.OutdoorsOnly = tmp105 != 0
	tmp106, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgnoreDeadMagicAndWildSurgeEffect = tmp106 != 0
	tmp107, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgnoreWildSurgeEffect = tmp107 != 0
	tmp108, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.NotInCombat = tmp108 != 0
	tmp109, err := this._io.ReadBitsIntLe(7)
	if err != nil {
		return err
	}
	this._unnamed9 = tmp109
	tmp110, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CanTargetInvisible = tmp110 != 0
	tmp111, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CastableWhenSilenced = tmp111 != 0
	tmp112, err := this._io.ReadBitsIntLe(6)
	if err != nil {
		return err
	}
	this._unnamed12 = tmp112
	return err
}
