// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package parser

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"io"
)


/**
 * WAVC is a container format used by Infinity Engine games to store compressed audio. It wraps an ACM-compressed audio
 * stream with a header that contains audio metadata (channels, sample rate, bits per sample) and size information.
 * Unlike ACM files, WAVC can be played from either the override folder or BIF files. WAVC files are 22050 Hz, 16 bits,
 * and must be renamed to *.WAV before being used in the game. The Infinity Engine plays WAVC files at twice the speed
 * of the original WAV file.
 * @see <a href="https://gibberlings3.github.io/iesdp/file_formats/ie_formats/wavc_v1.htm
 * ">Source</a>
 */
type Wavc struct {
	Magic []byte
	Version []byte
	UncompressedSize uint32
	LenAcmData uint32
	AcmOffset uint32
	NumChannels uint16
	BitsPerSample uint16
	SampleRate uint16
	Reserved uint16
	_io *kaitai.Stream
	_root *Wavc
	_parent kaitai.Struct
	_f_acmData bool
	acmData []byte
}
func NewWavc() *Wavc {
	return &Wavc{
	}
}

func (this Wavc) IO_() *kaitai.Stream {
	return this._io
}

func (this *Wavc) Read(io *kaitai.Stream, parent kaitai.Struct, root *Wavc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{87, 65, 86, 67})) {
		return kaitai.NewValidationNotEqualError([]uint8{87, 65, 86, 67}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = tmp2
	if !(bytes.Equal(this.Version, []uint8{86, 49, 46, 48})) {
		return kaitai.NewValidationNotEqualError([]uint8{86, 49, 46, 48}, this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.UncompressedSize = uint32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenAcmData = uint32(tmp4)
	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AcmOffset = uint32(tmp5)
	tmp6, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumChannels = uint16(tmp6)
	tmp7, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.BitsPerSample = uint16(tmp7)
	tmp8, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.SampleRate = uint16(tmp8)
	tmp9, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Reserved = uint16(tmp9)
	return err
}
func (this *Wavc) AcmData() (v []byte, err error) {
	if (this._f_acmData) {
		return this.acmData, nil
	}
	this._f_acmData = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.AcmOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp10, err := this._io.ReadBytes(int(this.LenAcmData))
	if err != nil {
		return nil, err
	}
	tmp10 = tmp10
	this.acmData = tmp10
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.acmData, nil
}
